In [563]:
import numpy as np
import pandas as pd

In [564]:
df=pd.read_csv("/home/user/Downloads/telecom_customer_churn.csv")

In [565]:
df.shape

(7043, 38)

In [566]:
df.columns

Index(['Customer ID', 'Gender', 'Age', 'Married', 'Number of Dependents',
       'City', 'Zip Code', 'Latitude', 'Longitude', 'Number of Referrals',
       'Tenure in Months', 'Offer', 'Phone Service',
       'Avg Monthly Long Distance Charges', 'Multiple Lines',
       'Internet Service', 'Internet Type', 'Avg Monthly GB Download',
       'Online Security', 'Online Backup', 'Device Protection Plan',
       'Premium Tech Support', 'Streaming TV', 'Streaming Movies',
       'Streaming Music', 'Unlimited Data', 'Contract', 'Paperless Billing',
       'Payment Method', 'Monthly Charge', 'Total Charges', 'Total Refunds',
       'Total Extra Data Charges', 'Total Long Distance Charges',
       'Total Revenue', 'Customer Status', 'Churn Category', 'Churn Reason'],
      dtype='object')

In [567]:
df.dtypes

Customer ID                           object
Gender                                object
Age                                    int64
Married                               object
Number of Dependents                   int64
City                                  object
Zip Code                               int64
Latitude                             float64
Longitude                            float64
Number of Referrals                    int64
Tenure in Months                       int64
Offer                                 object
Phone Service                         object
Avg Monthly Long Distance Charges    float64
Multiple Lines                        object
Internet Service                      object
Internet Type                         object
Avg Monthly GB Download              float64
Online Security                       object
Online Backup                         object
Device Protection Plan                object
Premium Tech Support                  object
Streaming TV                          object
Streaming Movies                      object
Streaming Music                       object
Unlimited Data                        object
Contract                              object
Paperless Billing                     object
Payment Method                        object
Monthly Charge                       float64
Total Charges                        float64
Total Refunds                        float64
Total Extra Data Charges               int64
Total Long Distance Charges          float64
Total Revenue                        float64
Customer Status                       object
Churn Category                        object
Churn Reason                          object
dtype: object

In [568]:
df.head()

,Customer ID,Gender,Age,Married,Number of Dependents,City,Zip Code,Latitude,Longitude,Number of Referrals,...,Payment Method,Monthly Charge,Total Charges,Total Refunds,Total Extra Data Charges,Total Long Distance Charges,Total Revenue,Customer Status,Churn Category,Churn Reason
0,0002-ORFBO,Female,37,Yes,0,Frazier Park,93225,34.827662,-118.999073,2,...,Credit Card,65.6,593.30,0.00,0,381.51,974.81,Stayed,NaN,NaN
1,0003-MKNFE,Male,46,No,0,Glendale,91206,34.162515,-118.203869,0,...,Credit Card,-4.0,542.40,38.33,10,96.21,610.28,Stayed,NaN,NaN
2,0004-TLHLJ,Male,50,No,0,Costa Mesa,92627,33.645672,-117.922613,0,...,Bank Withdrawal,73.9,280.85,0.00,0,134.60,415.45,Churned,Competitor,Competitor had better devices
3,0011-IGKFF,Male,78,Yes,0,Martinez,94553,38.014457,-122.115432,1,...,Bank Withdrawal,98.0,1237.85,0.00,0,361.66,1599.51,Churned,Dissatisfaction,Product dissatisfaction
4,0013-EXCHZ,Female,75,Yes,0,Camarillo,93010,34.227846,-119.079903,3,...,Credit Card,83.9,267.40,0.00,0,22.14,289.54,Churned,Dissatisfaction,Network reliability

In [569]:
df.head(10)

,Customer ID,Gender,Age,Married,Number of Dependents,City,Zip Code,Latitude,Longitude,Number of Referrals,...,Payment Method,Monthly Charge,Total Charges,Total Refunds,Total Extra Data Charges,Total Long Distance Charges,Total Revenue,Customer Status,Churn Category,Churn Reason
0,0002-ORFBO,Female,37,Yes,0,Frazier Park,93225,34.827662,-118.999073,2,...,Credit Card,65.60,593.30,0.00,0,381.51,974.81,Stayed,NaN,NaN
1,0003-MKNFE,Male,46,No,0,Glendale,91206,34.162515,-118.203869,0,...,Credit Card,-4.00,542.40,38.33,10,96.21,610.28,Stayed,NaN,NaN
2,0004-TLHLJ,Male,50,No,0,Costa Mesa,92627,33.645672,-117.922613,0,...,Bank Withdrawal,73.90,280.85,0.00,0,134.60,415.45,Churned,Competitor,Competitor had better devices
3,0011-IGKFF,Male,78,Yes,0,Martinez,94553,38.014457,-122.115432,1,...,Bank Withdrawal,98.00,1237.85,0.00,0,361.66,1599.51,Churned,Dissatisfaction,Product dissatisfaction
4,0013-EXCHZ,Female,75,Yes,0,Camarillo,93010,34.227846,-119.079903,3,...,Credit Card,83.90,267.40,0.00,0,22.14,289.54,Churned,Dissatisfaction,Network reliability
5,0013-MHZWF,Female,23,No,3,Midpines,95345,37.581496,-119.972762,0,...,Credit Card,69.40,571.45,0.00,0,150.93,722.38,Stayed,NaN,NaN
6,0013-SMEOE,Female,67,Yes,0,Lompoc,93437,34.757477,-120.550507,1,...,Bank Withdrawal,109.70,7904.25,0.00,0,707.16,8611.41,Stayed,NaN,NaN
7,0014-BMAQU,Male,52,Yes,0,Napa,94558,38.489789,-122.270110,8,...,Credit Card,84.65,5377.80,0.00,20,816.48,6214.28,Stayed,NaN,NaN
8,0015-UOCOJ,Female,68,No,0,Simi Valley,93063,34.296813,-118.685703,0,...,Bank Withdrawal,48.20,340.35,0.00,0,73.71,414.06,Stayed,NaN,NaN
9,0016-QLJIS,Female,43,Yes,1,Sheridan,95681,38.984756,-121.345074,3,...,Credit Card,90.45,5957.90,0.00,0,1849.90,7807.80,Stayed,NaN,NaN

In [570]:
df.head(-100)

,Customer ID,Gender,Age,Married,Number of Dependents,City,Zip Code,Latitude,Longitude,Number of Referrals,...,Payment Method,Monthly Charge,Total Charges,Total Refunds,Total Extra Data Charges,Total Long Distance Charges,Total Revenue,Customer Status,Churn Category,Churn Reason
0,0002-ORFBO,Female,37,Yes,0,Frazier Park,93225,34.827662,-118.999073,2,...,Credit Card,65.60,593.30,0.00,0,381.51,974.81,Stayed,NaN,NaN
1,0003-MKNFE,Male,46,No,0,Glendale,91206,34.162515,-118.203869,0,...,Credit Card,-4.00,542.40,38.33,10,96.21,610.28,Stayed,NaN,NaN
2,0004-TLHLJ,Male,50,No,0,Costa Mesa,92627,33.645672,-117.922613,0,...,Bank Withdrawal,73.90,280.85,0.00,0,134.60,415.45,Churned,Competitor,Competitor had better devices
3,0011-IGKFF,Male,78,Yes,0,Martinez,94553,38.014457,-122.115432,1,...,Bank Withdrawal,98.00,1237.85,0.00,0,361.66,1599.51,Churned,Dissatisfaction,Product dissatisfaction
4,0013-EXCHZ,Female,75,Yes,0,Camarillo,93010,34.227846,-119.079903,3,...,Credit Card,83.90,267.40,0.00,0,22.14,289.54,Churned,Dissatisfaction,Network reliability
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6938,9840-EFJQB,Female,43,No,0,Sylmar,91342,34.321621,-118.399841,0,...,Bank Withdrawal,74.35,74.35,0.00,0,24.41,98.76,Joined,NaN,NaN
6939,9842-EFSYY,Female,31,No,3,Markleeville,96120,38.735789,-119.857980,0,...,Credit Card,57.20,223.75,0.00,0,0.00,223.75,Stayed,NaN,NaN
6940,9844-FELAJ,Female,65,Yes,2,Sacramento,95833,38.619049,-121.517552,2,...,Bank Withdrawal,107.90,7475.85,0.00,20,658.00,8153.85,Stayed,NaN,NaN
6941,9845-PEEKO,Female,71,No,0,Brookdale,95007,37.106902,-122.100006,0,...,Credit Card,79.20,4590.35,0.00,0,361.67,4952.02,Stayed,NaN,NaN
6942,9845-QOMAD,Male,38,Yes,2,Long Beach,90814,33.771612,-118.143866,6,...,Credit Card,19.75,309.35,6.49,0,377.86,680.72,Stayed,NaN,NaN

In [571]:
df.tail()

,Customer ID,Gender,Age,Married,Number of Dependents,City,Zip Code,Latitude,Longitude,Number of Referrals,...,Payment Method,Monthly Charge,Total Charges,Total Refunds,Total Extra Data Charges,Total Long Distance Charges,Total Revenue,Customer Status,Churn Category,Churn Reason
7038,9987-LUTYD,Female,20,No,0,La Mesa,91941,32.759327,-116.997260,0,...,Credit Card,55.15,742.90,0.0,0,606.84,1349.74,Stayed,NaN,NaN
7039,9992-RRAMN,Male,40,Yes,0,Riverbank,95367,37.734971,-120.954271,1,...,Bank Withdrawal,85.10,1873.70,0.0,0,356.40,2230.10,Churned,Dissatisfaction,Product dissatisfaction
7040,9992-UJOEL,Male,22,No,0,Elk,95432,39.108252,-123.645121,0,...,Credit Card,50.30,92.75,0.0,0,37.24,129.99,Joined,NaN,NaN
7041,9993-LHIEB,Male,21,Yes,0,Solana Beach,92075,33.001813,-117.263628,5,...,Credit Card,67.85,4627.65,0.0,0,142.04,4769.69,Stayed,NaN,NaN
7042,9995-HOTOH,Male,36,Yes,0,Sierra City,96125,39.600599,-120.636358,1,...,Bank Withdrawal,59.00,3707.60,0.0,0,0.00,3707.60,Stayed,NaN,NaN

In [572]:
df.tail(10)

,Customer ID,Gender,Age,Married,Number of Dependents,City,Zip Code,Latitude,Longitude,Number of Referrals,...,Payment Method,Monthly Charge,Total Charges,Total Refunds,Total Extra Data Charges,Total Long Distance Charges,Total Revenue,Customer Status,Churn Category,Churn Reason
7033,9975-SKRNR,Male,24,No,0,Sierraville,96126,39.559709,-120.345639,0,...,Credit Card,18.90,18.90,0.0,0,49.51,68.41,Joined,NaN,NaN
7034,9978-HYCIN,Male,72,Yes,1,Bakersfield,93301,35.383937,-119.020428,1,...,Bank Withdrawal,84.95,4018.05,0.0,80,1987.63,6085.68,Stayed,NaN,NaN
7035,9979-RGMZT,Female,20,No,0,Los Angeles,90022,34.023810,-118.156582,0,...,Credit Card,94.05,633.45,0.0,0,255.43,888.88,Stayed,NaN,NaN
7036,9985-MWVIX,Female,53,No,0,Hume,93628,36.807595,-118.901544,0,...,Credit Card,70.15,70.15,0.0,0,42.09,112.24,Churned,Competitor,Competitor had better devices
7037,9986-BONCE,Female,36,No,0,Fallbrook,92028,33.362575,-117.299644,0,...,Bank Withdrawal,20.95,85.50,0.0,0,8.04,93.54,Churned,Competitor,Competitor made better offer
7038,9987-LUTYD,Female,20,No,0,La Mesa,91941,32.759327,-116.997260,0,...,Credit Card,55.15,742.90,0.0,0,606.84,1349.74,Stayed,NaN,NaN
7039,9992-RRAMN,Male,40,Yes,0,Riverbank,95367,37.734971,-120.954271,1,...,Bank Withdrawal,85.10,1873.70,0.0,0,356.40,2230.10,Churned,Dissatisfaction,Product dissatisfaction
7040,9992-UJOEL,Male,22,No,0,Elk,95432,39.108252,-123.645121,0,...,Credit Card,50.30,92.75,0.0,0,37.24,129.99,Joined,NaN,NaN
7041,9993-LHIEB,Male,21,Yes,0,Solana Beach,92075,33.001813,-117.263628,5,...,Credit Card,67.85,4627.65,0.0,0,142.04,4769.69,Stayed,NaN,NaN
7042,9995-HOTOH,Male,36,Yes,0,Sierra City,96125,39.600599,-120.636358,1,...,Bank Withdrawal,59.00,3707.60,0.0,0,0.00,3707.60,Stayed,NaN,NaN

In [573]:
df.tail(-100)

,Customer ID,Gender,Age,Married,Number of Dependents,City,Zip Code,Latitude,Longitude,Number of Referrals,...,Payment Method,Monthly Charge,Total Charges,Total Refunds,Total Extra Data Charges,Total Long Distance Charges,Total Revenue,Customer Status,Churn Category,Churn Reason
100,0178-CIIKR,Female,60,No,0,Crows Landing,95313,37.435664,-121.049056,0,...,Credit Card,19.95,58.00,0.0,0,8.07,66.07,Joined,NaN,NaN
101,0178-SZBHO,Male,54,Yes,1,Tuolumne,95379,37.939768,-120.188002,7,...,Bank Withdrawal,87.20,4017.45,0.0,0,51.23,4068.68,Stayed,NaN,NaN
102,0181-RITDD,Male,42,Yes,3,San Diego,92120,32.807867,-117.060993,2,...,Credit Card,108.15,6825.65,0.0,0,109.12,6934.77,Stayed,NaN,NaN
103,0186-CAERR,Male,22,No,0,Auburn,95603,38.912881,-121.082766,0,...,Bank Withdrawal,116.30,8309.55,0.0,0,204.48,8514.03,Stayed,NaN,NaN
104,0187-QSXOE,Male,71,Yes,0,Fresno,93725,36.623632,-119.741322,8,...,Bank Withdrawal,89.00,605.45,0.0,0,293.79,899.24,Stayed,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,9987-LUTYD,Female,20,No,0,La Mesa,91941,32.759327,-116.997260,0,...,Credit Card,55.15,742.90,0.0,0,606.84,1349.74,Stayed,NaN,NaN
7039,9992-RRAMN,Male,40,Yes,0,Riverbank,95367,37.734971,-120.954271,1,...,Bank Withdrawal,85.10,1873.70,0.0,0,356.40,2230.10,Churned,Dissatisfaction,Product dissatisfaction
7040,9992-UJOEL,Male,22,No,0,Elk,95432,39.108252,-123.645121,0,...,Credit Card,50.30,92.75,0.0,0,37.24,129.99,Joined,NaN,NaN
7041,9993-LHIEB,Male,21,Yes,0,Solana Beach,92075,33.001813,-117.263628,5,...,Credit Card,67.85,4627.65,0.0,0,142.04,4769.69,Stayed,NaN,NaN
7042,9995-HOTOH,Male,36,Yes,0,Sierra City,96125,39.600599,-120.636358,1,...,Bank Withdrawal,59.00,3707.60,0.0,0,0.00,3707.60,Stayed,NaN,NaN

In [574]:
df.describe()

,Age,Number of Dependents,Zip Code,Latitude,Longitude,Number of Referrals,Tenure in Months,Avg Monthly Long Distance Charges,Avg Monthly GB Download,Monthly Charge,Total Charges,Total Refunds,Total Extra Data Charges,Total Long Distance Charges,Total Revenue
count,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,6361.000000,5517.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000
mean,46.509726,0.468692,93486.070567,36.197455,-119.756684,1.951867,32.386767,25.420517,26.189958,63.596131,2280.381264,1.962182,6.860713,749.099262,3034.379056
std,16.750352,0.962802,1856.767505,2.468929,2.154425,3.001199,24.542061,14.200374,19.586585,31.204743,2266.220462,7.902614,25.104978,846.660055,2865.204542
min,19.000000,0.000000,90001.000000,32.555828,-124.301372,0.000000,1.000000,1.010000,2.000000,-10.000000,18.800000,0.000000,0.000000,0.000000,21.360000
25%,32.000000,0.000000,92101.000000,33.990646,-121.788090,0.000000,9.000000,13.050000,13.000000,30.400000,400.150000,0.000000,0.000000,70.545000,605.610000
50%,46.000000,0.000000,93518.000000,36.205465,-119.595293,0.000000,29.000000,25.690000,21.000000,70.050000,1394.550000,0.000000,0.000000,401.440000,2108.640000
75%,60.000000,0.000000,95329.000000,38.161321,-117.969795,3.000000,55.000000,37.680000,30.000000,89.750000,3786.600000,0.000000,0.000000,1191.100000,4801.145000
max,80.000000,9.000000,96150.000000,41.962127,-114.192901,11.000000,72.000000,49.990000,85.000000,118.750000,8684.800000,49.790000,150.000000,3564.720000,11979.340000

In [575]:
df.describe(include=[object])

,Customer ID,Gender,Married,City,Offer,Phone Service,Multiple Lines,Internet Service,Internet Type,Online Security,...,Streaming TV,Streaming Movies,Streaming Music,Unlimited Data,Contract,Paperless Billing,Payment Method,Customer Status,Churn Category,Churn Reason
count,7043,7043,7043,7043,3166,7043,6361,7043,5517,5517,...,5517,5517,5517,5517,7043,7043,7043,7043,1869,1869
unique,7043,2,2,1106,5,2,2,2,3,2,...,2,2,2,2,3,2,3,3,5,20
top,0002-ORFBO,Male,No,Los Angeles,Offer B,Yes,No,Yes,Fiber Optic,No,...,No,No,No,Yes,Month-to-Month,Yes,Bank Withdrawal,Stayed,Competitor,Competitor had better devices
freq,1,3555,3641,293,824,6361,3390,5517,3035,3498,...,2810,2785,3029,4745,3610,4171,3909,4720,841,313

In [576]:
df.describe(exclude=[object])

,Age,Number of Dependents,Zip Code,Latitude,Longitude,Number of Referrals,Tenure in Months,Avg Monthly Long Distance Charges,Avg Monthly GB Download,Monthly Charge,Total Charges,Total Refunds,Total Extra Data Charges,Total Long Distance Charges,Total Revenue
count,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,6361.000000,5517.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000
mean,46.509726,0.468692,93486.070567,36.197455,-119.756684,1.951867,32.386767,25.420517,26.189958,63.596131,2280.381264,1.962182,6.860713,749.099262,3034.379056
std,16.750352,0.962802,1856.767505,2.468929,2.154425,3.001199,24.542061,14.200374,19.586585,31.204743,2266.220462,7.902614,25.104978,846.660055,2865.204542
min,19.000000,0.000000,90001.000000,32.555828,-124.301372,0.000000,1.000000,1.010000,2.000000,-10.000000,18.800000,0.000000,0.000000,0.000000,21.360000
25%,32.000000,0.000000,92101.000000,33.990646,-121.788090,0.000000,9.000000,13.050000,13.000000,30.400000,400.150000,0.000000,0.000000,70.545000,605.610000
50%,46.000000,0.000000,93518.000000,36.205465,-119.595293,0.000000,29.000000,25.690000,21.000000,70.050000,1394.550000,0.000000,0.000000,401.440000,2108.640000
75%,60.000000,0.000000,95329.000000,38.161321,-117.969795,3.000000,55.000000,37.680000,30.000000,89.750000,3786.600000,0.000000,0.000000,1191.100000,4801.145000
max,80.000000,9.000000,96150.000000,41.962127,-114.192901,11.000000,72.000000,49.990000,85.000000,118.750000,8684.800000,49.790000,150.000000,3564.720000,11979.340000

In [577]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 38 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Customer ID                        7043 non-null   object
 1   Gender                             7043 non-null   object
 2   Age                                7043 non-null   int64
 3   Married                            7043 non-null   object
 4   Number of Dependents               7043 non-null   int64
 5   City                               7043 non-null   object
 6   Zip Code                           7043 non-null   int64
 7   Latitude                           7043 non-null   float64
 8   Longitude                          7043 non-null   float64
 9   Number of Referrals                7043 non-null   int64
 10  Tenure in Months                   7043 non-null   int64
 11  Offer                              3166 non-null   object
 12  Phone Service                      7043 non-null   object
 13  Avg Monthly Long Distance Charges  6361 non-null   float64
 14  Multiple Lines                     6361 non-null   object
 15  Internet Service                   7043 non-null   object
 16  Internet Type                      5517 non-null   object
 17  Avg Monthly GB Download            5517 non-null   float64
 18  Online Security                    5517 non-null   object
 19  Online Backup                      5517 non-null   object
 20  Device Protection Plan             5517 non-null   object
 21  Premium Tech Support               5517 non-null   object
 22  Streaming TV                       5517 non-null   object
 23  Streaming Movies                   5517 non-null   object
 24  Streaming Music                    5517 non-null   object
 25  Unlimited Data                     5517 non-null   object
 26  Contract                           7043 non-null   object
 27  Paperless Billing                  7043 non-null   object
 28  Payment Method                     7043 non-null   object
 29  Monthly Charge                     7043 non-null   float64
 30  Total Charges                      7043 non-null   float64
 31  Total Refunds                      7043 non-null   float64
 32  Total Extra Data Charges           7043 non-null   int64
 33  Total Long Distance Charges        7043 non-null   float64
 34  Total Revenue                      7043 non-null   float64
 35  Customer Status                    7043 non-null   object
 36  Churn Category                     1869 non-null   object
 37  Churn Reason                       1869 non-null   object
dtypes: float64(9), int64(6), object(23)
memory usage: 2.0+ MB

In [578]:
type(df["Gender"])

pandas.core.series.Series

In [579]:
df

,Customer ID,Gender,Age,Married,Number of Dependents,City,Zip Code,Latitude,Longitude,Number of Referrals,...,Payment Method,Monthly Charge,Total Charges,Total Refunds,Total Extra Data Charges,Total Long Distance Charges,Total Revenue,Customer Status,Churn Category,Churn Reason
0,0002-ORFBO,Female,37,Yes,0,Frazier Park,93225,34.827662,-118.999073,2,...,Credit Card,65.60,593.30,0.00,0,381.51,974.81,Stayed,NaN,NaN
1,0003-MKNFE,Male,46,No,0,Glendale,91206,34.162515,-118.203869,0,...,Credit Card,-4.00,542.40,38.33,10,96.21,610.28,Stayed,NaN,NaN
2,0004-TLHLJ,Male,50,No,0,Costa Mesa,92627,33.645672,-117.922613,0,...,Bank Withdrawal,73.90,280.85,0.00,0,134.60,415.45,Churned,Competitor,Competitor had better devices
3,0011-IGKFF,Male,78,Yes,0,Martinez,94553,38.014457,-122.115432,1,...,Bank Withdrawal,98.00,1237.85,0.00,0,361.66,1599.51,Churned,Dissatisfaction,Product dissatisfaction
4,0013-EXCHZ,Female,75,Yes,0,Camarillo,93010,34.227846,-119.079903,3,...,Credit Card,83.90,267.40,0.00,0,22.14,289.54,Churned,Dissatisfaction,Network reliability
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,9987-LUTYD,Female,20,No,0,La Mesa,91941,32.759327,-116.997260,0,...,Credit Card,55.15,742.90,0.00,0,606.84,1349.74,Stayed,NaN,NaN
7039,9992-RRAMN,Male,40,Yes,0,Riverbank,95367,37.734971,-120.954271,1,...,Bank Withdrawal,85.10,1873.70,0.00,0,356.40,2230.10,Churned,Dissatisfaction,Product dissatisfaction
7040,9992-UJOEL,Male,22,No,0,Elk,95432,39.108252,-123.645121,0,...,Credit Card,50.30,92.75,0.00,0,37.24,129.99,Joined,NaN,NaN
7041,9993-LHIEB,Male,21,Yes,0,Solana Beach,92075,33.001813,-117.263628,5,...,Credit Card,67.85,4627.65,0.00,0,142.04,4769.69,Stayed,NaN,NaN
7042,9995-HOTOH,Male,36,Yes,0,Sierra City,96125,39.600599,-120.636358,1,...,Bank Withdrawal,59.00,3707.60,0.00,0,0.00,3707.60,Stayed,NaN,NaN

In [580]:
df['Multiple Lines']=df['Multiple Lines'].replace({'Yes':1,'No':0})

/tmp/ipykernel_3896/3011508853.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Multiple Lines']=df['Multiple Lines'].replace({'Yes':1,'No':0})

In [581]:
df['Gender'] = df['Gender'].replace({'Female':1, 'Male':0})

/tmp/ipykernel_3896/4001803221.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Gender'] = df['Gender'].replace({'Female':1, 'Male':0})

In [582]:
df['Premium Tech Support'] = df['Premium Tech Support'].replace({'Yes':1, 'No':0})

/tmp/ipykernel_3896/2435158813.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Premium Tech Support'] = df['Premium Tech Support'].replace({'Yes':1, 'No':0})

In [583]:
df['Streaming TV'] = df['Streaming TV'].replace({'Yes':1, 'No':0})

/tmp/ipykernel_3896/2382689176.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Streaming TV'] = df['Streaming TV'].replace({'Yes':1, 'No':0})

In [584]:
df['Streaming Movies'] = df['Streaming Movies'].replace({'Yes':1, 'No':0})

/tmp/ipykernel_3896/1596363127.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Streaming Movies'] = df['Streaming Movies'].replace({'Yes':1, 'No':0})

In [585]:
df['Streaming Music'] = df['Streaming Music'].replace({'Yes':1, 'No':0})

/tmp/ipykernel_3896/3163307251.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Streaming Music'] = df['Streaming Music'].replace({'Yes':1, 'No':0})

In [586]:
df['Unlimited Data'] = df['Unlimited Data'].replace({'Yes':1, 'No':0})

/tmp/ipykernel_3896/2768738965.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Unlimited Data'] = df['Unlimited Data'].replace({'Yes':1, 'No':0})

In [587]:
df['Paperless Billing'] = df['Paperless Billing'].replace({'Yes':1, 'No':0})

/tmp/ipykernel_3896/1909443592.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Paperless Billing'] = df['Paperless Billing'].replace({'Yes':1, 'No':0})

In [588]:
df['Device Protection Plan'] = df['Device Protection Plan'].replace({'Yes':1, 'No':0})

/tmp/ipykernel_3896/4132773544.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Device Protection Plan'] = df['Device Protection Plan'].replace({'Yes':1, 'No':0})

In [589]:
df['Internet Service'] = df['Internet Service'].replace({'Yes':1, 'No':0})

/tmp/ipykernel_3896/1470666216.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Internet Service'] = df['Internet Service'].replace({'Yes':1, 'No':0})

In [590]:
df['Customer Status'] = df['Customer Status'].replace({'Churned':1, 'Joined':0,'Stayed':0})

/tmp/ipykernel_3896/2073798312.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Customer Status'] = df['Customer Status'].replace({'Churned':1, 'Joined':0,'Stayed':0})

In [591]:
df['Online Backup'] = df['Online Backup'].replace({'Yes':1, 'No':0})

/tmp/ipykernel_3896/8910303.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Online Backup'] = df['Online Backup'].replace({'Yes':1, 'No':0})

In [592]:
df['Online Security'] = df['Online Security'].replace({'Yes':1, 'No':0})

/tmp/ipykernel_3896/109156700.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Online Security'] = df['Online Security'].replace({'Yes':1, 'No':0})

In [593]:
df['Phone Service'] = df['Phone Service'].replace({'Yes':1, 'No':0})

/tmp/ipykernel_3896/2819535287.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Phone Service'] = df['Phone Service'].replace({'Yes':1, 'No':0})

In [594]:
df['Married'] = df['Married'].replace({'Yes':1, 'No':0})

/tmp/ipykernel_3896/279952452.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Married'] = df['Married'].replace({'Yes':1, 'No':0})

In [595]:
df['Total Revenue'].max()

11979.34

In [596]:
count=df["Total Revenue"].between(11000,120000).sum()
print(count)

27

In [597]:
count=df['Avg Monthly Long Distance Charges'].between(40,45).sum()
print(count)

647

In [598]:
count=df['Total Charges'].between(0,0.2).sum()
print(count)

0

In [599]:
count=df['Avg Monthly GB Download'].between(0,10).sum()
print(count)

1087

In [600]:
df['Gender'][200]

0

In [601]:
df.iloc[[980],[1]]

     Gender
980       0

In [602]:
df.iloc[1,8]

-118.203869

In [603]:
df.loc[980]

Customer ID                               1422-DGUBX
Gender                                             0
Age                                               64
Married                                            1
Number of Dependents                               0
City                                      Sacramento
Zip Code                                       95832
Latitude                                   38.445939
Longitude                                -121.496855
Number of Referrals                                4
Tenure in Months                                  32
Offer                                            NaN
Phone Service                                      1
Avg Monthly Long Distance Charges              43.11
Multiple Lines                                   1.0
Internet Service                                   1
Internet Type                            Fiber Optic
Avg Monthly GB Download                         18.0
Online Security                                  0.0
Online Backup                                    0.0
Device Protection Plan                           0.0
Premium Tech Support                             1.0
Streaming TV                                     0.0
Streaming Movies                                 0.0
Streaming Music                                  0.0
Unlimited Data                                   1.0
Contract                                    One Year
Paperless Billing                                  1
Payment Method                       Bank Withdrawal
Monthly Charge                                 79.25
Total Charges                                2619.15
Total Refunds                                  16.96
Total Extra Data Charges                           0
Total Long Distance Charges                  1379.52
Total Revenue                                3981.71
Customer Status                                    0
Churn Category                                   NaN
Churn Reason                                     NaN
Name: 980, dtype: object

In [604]:
df.loc[[980,456]]

,Customer ID,Gender,Age,Married,Number of Dependents,City,Zip Code,Latitude,Longitude,Number of Referrals,...,Payment Method,Monthly Charge,Total Charges,Total Refunds,Total Extra Data Charges,Total Long Distance Charges,Total Revenue,Customer Status,Churn Category,Churn Reason
980,1422-DGUBX,0,64,1,0,Sacramento,95832,38.445939,-121.496855,4,...,Bank Withdrawal,79.25,2619.15,16.96,0,1379.52,3981.71,0,NaN,NaN
456,0670-ANMUU,0,47,0,0,Chino Hills,91709,33.942895,-117.725644,0,...,Credit Card,97.65,6687.85,0.00,0,1176.47,7864.32,0,NaN,NaN

In [605]:
df.loc[[980,456],['Gender','Married']]

     Gender  Married
980       0        1
456       0        0

In [606]:
df.loc[45,'Longitude']

-119.372842

In [607]:
df[0:3]

,Customer ID,Gender,Age,Married,Number of Dependents,City,Zip Code,Latitude,Longitude,Number of Referrals,...,Payment Method,Monthly Charge,Total Charges,Total Refunds,Total Extra Data Charges,Total Long Distance Charges,Total Revenue,Customer Status,Churn Category,Churn Reason
0,0002-ORFBO,1,37,1,0,Frazier Park,93225,34.827662,-118.999073,2,...,Credit Card,65.6,593.30,0.00,0,381.51,974.81,0,NaN,NaN
1,0003-MKNFE,0,46,0,0,Glendale,91206,34.162515,-118.203869,0,...,Credit Card,-4.0,542.40,38.33,10,96.21,610.28,0,NaN,NaN
2,0004-TLHLJ,0,50,0,0,Costa Mesa,92627,33.645672,-117.922613,0,...,Bank Withdrawal,73.9,280.85,0.00,0,134.60,415.45,1,Competitor,Competitor had better devices

In [608]:
df.at[700,'Married']

1

In [609]:
df_copy=df.copy()
print(df_copy)

     Customer ID  Gender  Age  Married  Number of Dependents          City  \
0     0002-ORFBO       1   37        1                     0  Frazier Park
1     0003-MKNFE       0   46        0                     0      Glendale
2     0004-TLHLJ       0   50        0                     0    Costa Mesa
3     0011-IGKFF       0   78        1                     0      Martinez
4     0013-EXCHZ       1   75        1                     0     Camarillo
...          ...     ...  ...      ...                   ...           ...
7038  9987-LUTYD       1   20        0                     0       La Mesa
7039  9992-RRAMN       0   40        1                     0     Riverbank
7040  9992-UJOEL       0   22        0                     0           Elk
7041  9993-LHIEB       0   21        1                     0  Solana Beach
7042  9995-HOTOH       0   36        1                     0   Sierra City

      Zip Code   Latitude   Longitude  Number of Referrals  ...  \
0        93225  34.827662 -118.999073                    2  ...
1        91206  34.162515 -118.203869                    0  ...
2        92627  33.645672 -117.922613                    0  ...
3        94553  38.014457 -122.115432                    1  ...
4        93010  34.227846 -119.079903                    3  ...
...        ...        ...         ...                  ...  ...
7038     91941  32.759327 -116.997260                    0  ...
7039     95367  37.734971 -120.954271                    1  ...
7040     95432  39.108252 -123.645121                    0  ...
7041     92075  33.001813 -117.263628                    5  ...
7042     96125  39.600599 -120.636358                    1  ...

       Payment Method Monthly Charge  Total Charges  Total Refunds  \
0         Credit Card          65.60         593.30           0.00
1         Credit Card          -4.00         542.40          38.33
2     Bank Withdrawal          73.90         280.85           0.00
3     Bank Withdrawal          98.00        1237.85           0.00
4         Credit Card          83.90         267.40           0.00
...               ...            ...            ...            ...
7038      Credit Card          55.15         742.90           0.00
7039  Bank Withdrawal          85.10        1873.70           0.00
7040      Credit Card          50.30          92.75           0.00
7041      Credit Card          67.85        4627.65           0.00
7042  Bank Withdrawal          59.00        3707.60           0.00

      Total Extra Data Charges  Total Long Distance Charges Total Revenue  \
0                            0                       381.51        974.81
1                           10                        96.21        610.28
2                            0                       134.60        415.45
3                            0                       361.66       1599.51
4                            0                        22.14        289.54
...                        ...                          ...           ...
7038                         0                       606.84       1349.74
7039                         0                       356.40       2230.10
7040                         0                        37.24        129.99
7041                         0                       142.04       4769.69
7042                         0                         0.00       3707.60

      Customer Status   Churn Category                   Churn Reason
0                   0              NaN                            NaN
1                   0              NaN                            NaN
2                   1       Competitor  Competitor had better devices
3                   1  Dissatisfaction        Product dissatisfaction
4                   1  Dissatisfaction            Network reliability
...               ...              ...                            ...
7038                0              NaN                            NaN
7039                1  Dissatisfaction        Product dissatisfaction
7040                0              NaN                            NaN
7041                0              NaN                            NaN
7042                0              NaN                            NaN

[7043 rows x 38 columns]

In [610]:
print(df_copy.at[500,"Gender"])

0

In [611]:
df_copy.at[500,'Gender']='1'
df_copy.iloc[[500],[1]]

/tmp/ipykernel_3896/2115361419.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df_copy.at[500,'Gender']='1'

    Gender
500      1

In [612]:
df_copy.at[500,'Gender']

'1'

In [613]:
print(df.at[500,"Gender"])

0

In [614]:
df[0:3]

,Customer ID,Gender,Age,Married,Number of Dependents,City,Zip Code,Latitude,Longitude,Number of Referrals,...,Payment Method,Monthly Charge,Total Charges,Total Refunds,Total Extra Data Charges,Total Long Distance Charges,Total Revenue,Customer Status,Churn Category,Churn Reason
0,0002-ORFBO,1,37,1,0,Frazier Park,93225,34.827662,-118.999073,2,...,Credit Card,65.6,593.30,0.00,0,381.51,974.81,0,NaN,NaN
1,0003-MKNFE,0,46,0,0,Glendale,91206,34.162515,-118.203869,0,...,Credit Card,-4.0,542.40,38.33,10,96.21,610.28,0,NaN,NaN
2,0004-TLHLJ,0,50,0,0,Costa Mesa,92627,33.645672,-117.922613,0,...,Bank Withdrawal,73.9,280.85,0.00,0,134.60,415.45,1,Competitor,Competitor had better devices

In [615]:
df.loc[7:9]

,Customer ID,Gender,Age,Married,Number of Dependents,City,Zip Code,Latitude,Longitude,Number of Referrals,...,Payment Method,Monthly Charge,Total Charges,Total Refunds,Total Extra Data Charges,Total Long Distance Charges,Total Revenue,Customer Status,Churn Category,Churn Reason
7,0014-BMAQU,0,52,1,0,Napa,94558,38.489789,-122.270110,8,...,Credit Card,84.65,5377.80,0.0,20,816.48,6214.28,0,NaN,NaN
8,0015-UOCOJ,1,68,0,0,Simi Valley,93063,34.296813,-118.685703,0,...,Bank Withdrawal,48.20,340.35,0.0,0,73.71,414.06,0,NaN,NaN
9,0016-QLJIS,1,43,1,1,Sheridan,95681,38.984756,-121.345074,3,...,Credit Card,90.45,5957.90,0.0,0,1849.90,7807.80,0,NaN,NaN

In [616]:
df.loc[23:45,'Gender']

23    1
24    1
25    1
26    1
27    0
28    0
29    1
30    0
31    1
32    0
33    1
34    0
35    1
36    1
37    1
38    1
39    0
40    0
41    1
42    0
43    0
44    0
45    0
Name: Gender, dtype: int64

In [617]:
df.loc[10:20,"Gender":"Payment Method"]

,Gender,Age,Married,Number of Dependents,City,Zip Code,Latitude,Longitude,Number of Referrals,Tenure in Months,...,Online Backup,Device Protection Plan,Premium Tech Support,Streaming TV,Streaming Movies,Streaming Music,Unlimited Data,Contract,Paperless Billing,Payment Method
10,0,47,0,0,Rancho Santa Fe,92091,32.993560,-117.207121,0,54,...,0.0,0.0,1.0,1.0,0.0,0.0,1.0,Two Year,0,Credit Card
11,1,25,1,2,Sunnyvale,94086,37.378541,-122.020456,2,72,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,Two Year,1,Credit Card
12,1,58,1,0,Antelope,95843,38.715498,-121.363411,0,5,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,Month-to-Month,1,Bank Withdrawal
13,1,32,0,0,La Mesa,91942,32.782501,-117.016110,0,72,...,1.0,1.0,0.0,1.0,0.0,0.0,1.0,Two Year,1,Bank Withdrawal
14,1,39,0,0,Los Olivos,93441,34.704340,-120.026090,0,56,...,1.0,1.0,1.0,0.0,0.0,0.0,1.0,Two Year,0,Bank Withdrawal
15,1,58,1,2,Woodlake,93286,36.464635,-119.094348,9,71,...,1.0,1.0,0.0,0.0,1.0,1.0,1.0,Two Year,1,Credit Card
16,1,52,1,1,Point Reyes Station,94956,38.060264,-122.830646,0,34,...,0.0,1.0,1.0,1.0,1.0,1.0,1.0,One Year,0,Credit Card
17,1,72,0,0,San Marcos,92078,33.119028,-117.166036,0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,One Year,1,Bank Withdrawal
18,0,79,0,0,Daly City,94015,37.680844,-122.481310,0,45,...,0.0,1.0,0.0,0.0,1.0,0.0,1.0,One Year,0,Credit Card
19,0,67,0,0,Morgan Hill,95037,37.161544,-121.649371,0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,Month-to-Month,1,Bank Withdrawal
20,1,79,1,0,Ahwahnee,93601,37.375816,-119.739935,0,50,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,One Year,0,Bank Withdrawal

In [618]:
df.iloc[1:2,0:3]

  Customer ID  Gender  Age
1  0003-MKNFE       0   46

In [619]:
df.iloc[1,0:3]

Customer ID    0003-MKNFE
Gender                  0
Age                    46
Name: 1, dtype: object

DATA CLEANING


HANDLING MISSING VALUES..

In [620]:
df.isna()

,Customer ID,Gender,Age,Married,Number of Dependents,City,Zip Code,Latitude,Longitude,Number of Referrals,...,Payment Method,Monthly Charge,Total Charges,Total Refunds,Total Extra Data Charges,Total Long Distance Charges,Total Revenue,Customer Status,Churn Category,Churn Reason
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,True
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,True
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,True
7039,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7040,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,True
7041,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,True
7042,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,True

In [621]:
df["Payment Method"].isna()

0       False
1       False
2       False
3       False
4       False
        ...
7038    False
7039    False
7040    False
7041    False
7042    False
Name: Payment Method, Length: 7043, dtype: bool

In [622]:
df.isna().sum()

Customer ID                             0
Gender                                  0
Age                                     0
Married                                 0
Number of Dependents                    0
City                                    0
Zip Code                                0
Latitude                                0
Longitude                               0
Number of Referrals                     0
Tenure in Months                        0
Offer                                3877
Phone Service                           0
Avg Monthly Long Distance Charges     682
Multiple Lines                        682
Internet Service                        0
Internet Type                        1526
Avg Monthly GB Download              1526
Online Security                      1526
Online Backup                        1526
Device Protection Plan               1526
Premium Tech Support                 1526
Streaming TV                         1526
Streaming Movies                     1526
Streaming Music                      1526
Unlimited Data                       1526
Contract                                0
Paperless Billing                       0
Payment Method                          0
Monthly Charge                          0
Total Charges                           0
Total Refunds                           0
Total Extra Data Charges                0
Total Long Distance Charges             0
Total Revenue                           0
Customer Status                         0
Churn Category                       5174
Churn Reason                         5174
dtype: int64

In [623]:
#df.fillna("Missing")

In [624]:
#values={"Offer":'No Offer','Avg Monthly Long Distance Charges':'0','Multiple Lines':'0','Internet Type':'no cable connection','Avg Monthly GB Download':'0','Online Security':'No','Online Backup':'No','Device Protection Plan':'No','Premium Tech Support':"No",'Streaming TV':'No','Streaming Movies':'No','Streaming Music':'No','Churn Category':'No','Churn Reason':'No'}
#df.fillna(value=values).head(10)

In [625]:
(df.isnull().sum() / len(df)) * 100

Customer ID                           0.000000
Gender                                0.000000
Age                                   0.000000
Married                               0.000000
Number of Dependents                  0.000000
City                                  0.000000
Zip Code                              0.000000
Latitude                              0.000000
Longitude                             0.000000
Number of Referrals                   0.000000
Tenure in Months                      0.000000
Offer                                55.047565
Phone Service                         0.000000
Avg Monthly Long Distance Charges     9.683374
Multiple Lines                        9.683374
Internet Service                      0.000000
Internet Type                        21.666903
Avg Monthly GB Download              21.666903
Online Security                      21.666903
Online Backup                        21.666903
Device Protection Plan               21.666903
Premium Tech Support                 21.666903
Streaming TV                         21.666903
Streaming Movies                     21.666903
Streaming Music                      21.666903
Unlimited Data                       21.666903
Contract                              0.000000
Paperless Billing                     0.000000
Payment Method                        0.000000
Monthly Charge                        0.000000
Total Charges                         0.000000
Total Refunds                         0.000000
Total Extra Data Charges              0.000000
Total Long Distance Charges           0.000000
Total Revenue                         0.000000
Customer Status                       0.000000
Churn Category                       73.463013
Churn Reason                         73.463013
dtype: float64

In [626]:
df.loc[23:50,"Latitude"]

23    36.560498
24    40.766600
25    33.309852
26    36.622237
27    37.612612
28    38.368744
29    40.737431
30    37.515556
31    34.001617
32    34.044271
33    32.690654
34    40.677649
35    37.084697
36    38.044523
37    33.964131
38    33.978030
39    35.013299
40    32.961064
41    37.516791
42    38.439696
43    37.327069
44    34.296574
45    36.391777
46    38.123544
47    37.654551
48    38.629618
49    37.956963
50    41.813521
Name: Latitude, dtype: float64

**Filling  Numeric Null values with Mean**

In [627]:
df.fillna(df.mean(numeric_only=True), inplace=True)

In [628]:
df['Avg Monthly Long Distance Charges'].fillna(df['Avg Monthly Long Distance Charges'].mode()[0], inplace=True)
df['Avg Monthly Long Distance Charges']

/tmp/ipykernel_3896/974455266.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Avg Monthly Long Distance Charges'].fillna(df['Avg Monthly Long Distance Charges'].mode()[0], inplace=True)

0       42.390000
1       10.690000
2       33.650000
3       27.820000
4        7.380000
          ...
7038    46.680000
7039    16.200000
7040    18.620000
7041     2.120000
7042    25.420517
Name: Avg Monthly Long Distance Charges, Length: 7043, dtype: float64

In [629]:
cat_cols = df.select_dtypes(include='object').columns

In [630]:
df[cat_cols] = df[cat_cols].fillna(df[cat_cols].mode().iloc[0])

Drop Null Values

In [631]:
df.dropna()

,Customer ID,Gender,Age,Married,Number of Dependents,City,Zip Code,Latitude,Longitude,Number of Referrals,...,Payment Method,Monthly Charge,Total Charges,Total Refunds,Total Extra Data Charges,Total Long Distance Charges,Total Revenue,Customer Status,Churn Category,Churn Reason
0,0002-ORFBO,1,37,1,0,Frazier Park,93225,34.827662,-118.999073,2,...,Credit Card,65.60,593.30,0.00,0,381.51,974.81,0,Competitor,Competitor had better devices
1,0003-MKNFE,0,46,0,0,Glendale,91206,34.162515,-118.203869,0,...,Credit Card,-4.00,542.40,38.33,10,96.21,610.28,0,Competitor,Competitor had better devices
2,0004-TLHLJ,0,50,0,0,Costa Mesa,92627,33.645672,-117.922613,0,...,Bank Withdrawal,73.90,280.85,0.00,0,134.60,415.45,1,Competitor,Competitor had better devices
3,0011-IGKFF,0,78,1,0,Martinez,94553,38.014457,-122.115432,1,...,Bank Withdrawal,98.00,1237.85,0.00,0,361.66,1599.51,1,Dissatisfaction,Product dissatisfaction
4,0013-EXCHZ,1,75,1,0,Camarillo,93010,34.227846,-119.079903,3,...,Credit Card,83.90,267.40,0.00,0,22.14,289.54,1,Dissatisfaction,Network reliability
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,9987-LUTYD,1,20,0,0,La Mesa,91941,32.759327,-116.997260,0,...,Credit Card,55.15,742.90,0.00,0,606.84,1349.74,0,Competitor,Competitor had better devices
7039,9992-RRAMN,0,40,1,0,Riverbank,95367,37.734971,-120.954271,1,...,Bank Withdrawal,85.10,1873.70,0.00,0,356.40,2230.10,1,Dissatisfaction,Product dissatisfaction
7040,9992-UJOEL,0,22,0,0,Elk,95432,39.108252,-123.645121,0,...,Credit Card,50.30,92.75,0.00,0,37.24,129.99,0,Competitor,Competitor had better devices
7041,9993-LHIEB,0,21,1,0,Solana Beach,92075,33.001813,-117.263628,5,...,Credit Card,67.85,4627.65,0.00,0,142.04,4769.69,0,Competitor,Competitor had better devices
7042,9995-HOTOH,0,36,1,0,Sierra City,96125,39.600599,-120.636358,1,...,Bank Withdrawal,59.00,3707.60,0.00,0,0.00,3707.60,0,Competitor,Competitor had better devices

In [632]:
df.dropna(how='all')

,Customer ID,Gender,Age,Married,Number of Dependents,City,Zip Code,Latitude,Longitude,Number of Referrals,...,Payment Method,Monthly Charge,Total Charges,Total Refunds,Total Extra Data Charges,Total Long Distance Charges,Total Revenue,Customer Status,Churn Category,Churn Reason
0,0002-ORFBO,1,37,1,0,Frazier Park,93225,34.827662,-118.999073,2,...,Credit Card,65.60,593.30,0.00,0,381.51,974.81,0,Competitor,Competitor had better devices
1,0003-MKNFE,0,46,0,0,Glendale,91206,34.162515,-118.203869,0,...,Credit Card,-4.00,542.40,38.33,10,96.21,610.28,0,Competitor,Competitor had better devices
2,0004-TLHLJ,0,50,0,0,Costa Mesa,92627,33.645672,-117.922613,0,...,Bank Withdrawal,73.90,280.85,0.00,0,134.60,415.45,1,Competitor,Competitor had better devices
3,0011-IGKFF,0,78,1,0,Martinez,94553,38.014457,-122.115432,1,...,Bank Withdrawal,98.00,1237.85,0.00,0,361.66,1599.51,1,Dissatisfaction,Product dissatisfaction
4,0013-EXCHZ,1,75,1,0,Camarillo,93010,34.227846,-119.079903,3,...,Credit Card,83.90,267.40,0.00,0,22.14,289.54,1,Dissatisfaction,Network reliability
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,9987-LUTYD,1,20,0,0,La Mesa,91941,32.759327,-116.997260,0,...,Credit Card,55.15,742.90,0.00,0,606.84,1349.74,0,Competitor,Competitor had better devices
7039,9992-RRAMN,0,40,1,0,Riverbank,95367,37.734971,-120.954271,1,...,Bank Withdrawal,85.10,1873.70,0.00,0,356.40,2230.10,1,Dissatisfaction,Product dissatisfaction
7040,9992-UJOEL,0,22,0,0,Elk,95432,39.108252,-123.645121,0,...,Credit Card,50.30,92.75,0.00,0,37.24,129.99,0,Competitor,Competitor had better devices
7041,9993-LHIEB,0,21,1,0,Solana Beach,92075,33.001813,-117.263628,5,...,Credit Card,67.85,4627.65,0.00,0,142.04,4769.69,0,Competitor,Competitor had better devices
7042,9995-HOTOH,0,36,1,0,Sierra City,96125,39.600599,-120.636358,1,...,Bank Withdrawal,59.00,3707.60,0.00,0,0.00,3707.60,0,Competitor,Competitor had better devices

In [633]:
df.dropna(axis='columns',how='any')

,Customer ID,Gender,Age,Married,Number of Dependents,City,Zip Code,Latitude,Longitude,Number of Referrals,...,Payment Method,Monthly Charge,Total Charges,Total Refunds,Total Extra Data Charges,Total Long Distance Charges,Total Revenue,Customer Status,Churn Category,Churn Reason
0,0002-ORFBO,1,37,1,0,Frazier Park,93225,34.827662,-118.999073,2,...,Credit Card,65.60,593.30,0.00,0,381.51,974.81,0,Competitor,Competitor had better devices
1,0003-MKNFE,0,46,0,0,Glendale,91206,34.162515,-118.203869,0,...,Credit Card,-4.00,542.40,38.33,10,96.21,610.28,0,Competitor,Competitor had better devices
2,0004-TLHLJ,0,50,0,0,Costa Mesa,92627,33.645672,-117.922613,0,...,Bank Withdrawal,73.90,280.85,0.00,0,134.60,415.45,1,Competitor,Competitor had better devices
3,0011-IGKFF,0,78,1,0,Martinez,94553,38.014457,-122.115432,1,...,Bank Withdrawal,98.00,1237.85,0.00,0,361.66,1599.51,1,Dissatisfaction,Product dissatisfaction
4,0013-EXCHZ,1,75,1,0,Camarillo,93010,34.227846,-119.079903,3,...,Credit Card,83.90,267.40,0.00,0,22.14,289.54,1,Dissatisfaction,Network reliability
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,9987-LUTYD,1,20,0,0,La Mesa,91941,32.759327,-116.997260,0,...,Credit Card,55.15,742.90,0.00,0,606.84,1349.74,0,Competitor,Competitor had better devices
7039,9992-RRAMN,0,40,1,0,Riverbank,95367,37.734971,-120.954271,1,...,Bank Withdrawal,85.10,1873.70,0.00,0,356.40,2230.10,1,Dissatisfaction,Product dissatisfaction
7040,9992-UJOEL,0,22,0,0,Elk,95432,39.108252,-123.645121,0,...,Credit Card,50.30,92.75,0.00,0,37.24,129.99,0,Competitor,Competitor had better devices
7041,9993-LHIEB,0,21,1,0,Solana Beach,92075,33.001813,-117.263628,5,...,Credit Card,67.85,4627.65,0.00,0,142.04,4769.69,0,Competitor,Competitor had better devices
7042,9995-HOTOH,0,36,1,0,Sierra City,96125,39.600599,-120.636358,1,...,Bank Withdrawal,59.00,3707.60,0.00,0,0.00,3707.60,0,Competitor,Competitor had better devices

In [634]:
df.dropna(subset=['Churn Reason','Churn Category'])

,Customer ID,Gender,Age,Married,Number of Dependents,City,Zip Code,Latitude,Longitude,Number of Referrals,...,Payment Method,Monthly Charge,Total Charges,Total Refunds,Total Extra Data Charges,Total Long Distance Charges,Total Revenue,Customer Status,Churn Category,Churn Reason
0,0002-ORFBO,1,37,1,0,Frazier Park,93225,34.827662,-118.999073,2,...,Credit Card,65.60,593.30,0.00,0,381.51,974.81,0,Competitor,Competitor had better devices
1,0003-MKNFE,0,46,0,0,Glendale,91206,34.162515,-118.203869,0,...,Credit Card,-4.00,542.40,38.33,10,96.21,610.28,0,Competitor,Competitor had better devices
2,0004-TLHLJ,0,50,0,0,Costa Mesa,92627,33.645672,-117.922613,0,...,Bank Withdrawal,73.90,280.85,0.00,0,134.60,415.45,1,Competitor,Competitor had better devices
3,0011-IGKFF,0,78,1,0,Martinez,94553,38.014457,-122.115432,1,...,Bank Withdrawal,98.00,1237.85,0.00,0,361.66,1599.51,1,Dissatisfaction,Product dissatisfaction
4,0013-EXCHZ,1,75,1,0,Camarillo,93010,34.227846,-119.079903,3,...,Credit Card,83.90,267.40,0.00,0,22.14,289.54,1,Dissatisfaction,Network reliability
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,9987-LUTYD,1,20,0,0,La Mesa,91941,32.759327,-116.997260,0,...,Credit Card,55.15,742.90,0.00,0,606.84,1349.74,0,Competitor,Competitor had better devices
7039,9992-RRAMN,0,40,1,0,Riverbank,95367,37.734971,-120.954271,1,...,Bank Withdrawal,85.10,1873.70,0.00,0,356.40,2230.10,1,Dissatisfaction,Product dissatisfaction
7040,9992-UJOEL,0,22,0,0,Elk,95432,39.108252,-123.645121,0,...,Credit Card,50.30,92.75,0.00,0,37.24,129.99,0,Competitor,Competitor had better devices
7041,9993-LHIEB,0,21,1,0,Solana Beach,92075,33.001813,-117.263628,5,...,Credit Card,67.85,4627.65,0.00,0,142.04,4769.69,0,Competitor,Competitor had better devices
7042,9995-HOTOH,0,36,1,0,Sierra City,96125,39.600599,-120.636358,1,...,Bank Withdrawal,59.00,3707.60,0.00,0,0.00,3707.60,0,Competitor,Competitor had better devices

HANDLING DUPLICATES

In [635]:
df[25:37].duplicated()

25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
dtype: bool

In [636]:
df[25:37].duplicated(keep='last')

25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
dtype: bool

In [637]:
df[0:10].duplicated(subset=['Gender'])

0    False
1    False
2     True
3     True
4     True
5     True
6     True
7     True
8     True
9     True
dtype: bool

Drop Duplicates

In [638]:
tel_df=df[25:78]
tel_df

,Customer ID,Gender,Age,Married,Number of Dependents,City,Zip Code,Latitude,Longitude,Number of Referrals,...,Payment Method,Monthly Charge,Total Charges,Total Refunds,Total Extra Data Charges,Total Long Distance Charges,Total Revenue,Customer Status,Churn Category,Churn Reason
25,0032-PGELS,1,37,1,1,Palomar Mountain,92060,33.309852,-116.823091,1,...,Bank Withdrawal,30.50,30.50,0.00,0,0.00,30.50,1,Attitude,Attitude of service provider
26,0036-IHMOT,1,37,1,3,Parlier,93648,36.622237,-119.521126,10,...,Bank Withdrawal,103.70,5656.75,0.00,20,1927.20,7603.95,0,Competitor,Competitor had better devices
27,0040-HALCW,0,42,1,3,Modesto,95358,37.612612,-121.108568,3,...,Credit Card,20.40,1090.60,0.00,0,1063.80,2154.40,0,Competitor,Competitor had better devices
28,0042-JVWOJ,0,64,0,0,Glen Ellen,95442,38.368744,-122.522642,0,...,Bank Withdrawal,19.60,471.85,21.25,0,980.20,1430.80,0,Competitor,Competitor had better devices
29,0042-RLHYP,1,47,1,3,Eureka,95503,40.737431,-124.108897,5,...,Bank Withdrawal,19.70,1396.90,0.00,0,2648.91,4045.81,0,Competitor,Competitor had better devices
30,0048-LUMLS,0,23,1,3,Moss Beach,94038,37.515556,-122.502311,1,...,Credit Card,91.20,3247.55,0.00,0,1591.37,4838.92,0,Competitor,Competitor had better devices
31,0048-PIHNL,1,48,1,0,Los Angeles,90058,34.001617,-118.222274,5,...,Bank Withdrawal,20.45,900.90,0.00,0,2429.42,3330.32,0,Competitor,Competitor had better devices
32,0052-DCKON,0,28,1,0,Los Angeles,90063,34.044271,-118.185237,9,...,Bank Withdrawal,-2.00,7942.15,0.00,0,2888.82,10830.97,0,Competitor,Competitor had better devices
33,0052-YNYOT,1,28,0,0,Calexico,92231,32.690654,-115.431225,0,...,Bank Withdrawal,20.55,1343.40,30.53,0,1549.04,2861.91,0,Competitor,Competitor had better devices
34,0056-EPFBG,0,33,1,1,Redding,96003,40.677649,-122.294670,4,...,Credit Card,39.40,825.40,0.00,0,0.00,825.40,0,Competitor,Competitor had better devices
35,0057-QBUQH,1,31,0,3,San Martin,95046,37.084697,-121.606417,0,...,Bank Withdrawal,25.10,1070.15,0.00,0,1317.52,2387.67,0,Competitor,Competitor had better devices
36,0058-EVZWM,1,37,1,0,Stockton,95209,38.044523,-121.348048,2,...,Bank Withdrawal,89.80,4959.60,0.00,0,279.40,5239.00,0,Competitor,Competitor had better devices
37,0060-FUALY,1,60,1,0,Los Angeles,90003,33.964131,-118.272783,4,...,Bank Withdrawal,94.75,5597.65,0.00,0,967.01,6564.66,0,Competitor,Competitor had better devices
38,0064-SUDOG,1,48,1,3,Huntington Park,90255,33.978030,-118.217141,3,...,Bank Withdrawal,20.30,224.50,0.00,0,231.36,455.86,0,Competitor,Competitor had better devices
39,0064-YIJGF,0,60,1,3,Yermo,92398,35.013299,-116.834092,7,...,Bank Withdrawal,75.75,1929.00,0.00,0,682.02,2611.02,0,Competitor,Competitor had better devices
40,0067-DKWBL,0,69,0,0,San Diego,92129,32.961064,-117.134917,0,...,Bank Withdrawal,49.25,91.10,0.00,0,87.98,179.08,1,Competitor,Competitor made better offer
41,0068-FIGTF,1,20,0,0,Fremont,94539,37.516791,-121.899117,0,...,Credit Card,78.20,2078.95,0.00,0,1320.57,3399.52,0,Competitor,Competitor had better devices
42,0071-NDAFP,0,31,1,3,Santa Rosa,95405,38.439696,-122.668817,1,...,Credit Card,25.50,630.60,44.42,0,592.25,1178.43,0,Competitor,Competitor had better devices
43,0074-HDKDG,0,46,1,0,San Jose,95126,37.327069,-121.916819,5,...,Bank Withdrawal,61.60,1611.00,44.90,0,161.25,1727.35,0,Competitor,Competitor had better devices
44,0076-LVEPS,0,57,0,1,Tujunga,91042,34.296574,-118.244839,0,...,Credit Card,45.00,1242.45,12.26,0,0.00,1230.19,0,Competitor,Competitor had better devices
45,0078-XZMHT,0,19,1,0,Visalia,93291,36.391777,-119.372842,5,...,Bank Withdrawal,85.15,6316.20,0.00,0,2329.92,8646.12,0,Competitor,Competitor had better devices
46,0080-EMYVY,1,64,0,0,Lodi,95240,38.123544,-121.159078,0,...,Credit Card,51.45,727.85,0.00,0,336.56,1064.41,0,Competitor,Competitor had better devices
47,0080-OROZO,1,38,0,0,El Portal,95318,37.654551,-119.822984,0,...,Bank Withdrawal,99.25,3532.00,0.00,0,1274.70,4806.70,0,Competitor,Competitor had better devices
48,0082-LDZUE,0,54,0,0,Calistoga,94515,38.629618,-122.593216,0,...,Credit Card,44.30,44.30,0.00,0,42.95,87.25,0,Competitor,Competitor had better devices
49,0082-OQIQY,0,50,0,0,Farmington,95230,37.956963,-120.863055,0,...,Bank Withdrawal,94.20,2607.60,0.00,20,59.45,2687.05,0,Competitor,Competitor had better devices
50,0083-PIVIK,0,25,0,0,Tulelake,96134,41.813521,-121.492666,0,...,Bank Withdrawal,81.25,5567.55,0.00,40,351.36,5958.91,0,Competitor,Competitor had better devices
51,0089-IIQKO,1,35,1,3,Coleville,96107,38.425280,-119.475741,1,...,Credit Card,99.95,3767.40,0.00,0,950.82,4718.22,0,Competitor,Competitor had better devices
52,0093-EXYQL,1,72,0,0,Ojai,93023,34.581308,-118.931948,0,...,Bank Withdrawal,91.55,3673.60,0.00,0,1765.60,5439.20,0,Competitor,Competitor had better devices
53,0093-XWZFY,0,51,0,0,Desert Hot Springs,92241,33.832799,-116.250973,0,...,Credit Card,104.50,4036.85,0.00,0,1507.60,5544.45,1,Competitor,Competitor had better devices
54,0094-OIFMO,1,78,0,1,North Hollywood,91605,34.207295,-118.400022,0,...,Bank Withdrawal,95.00,1120.30,0.00,120,127.49,1367.79,1,Dissatisfaction,Product dissatisfaction
55,0096-BXERS,1,30,1,0,Inverness,94937,38.099323,-122.945723,10,...,Bank Withdrawal,50.35,314.55,0.00,0,255.96,570.51,0,Competitor,Competitor had better devices
56,0096-FCPUF,0,58,0,0,Santa Rosa,95404,38.526941,-122.709096,0,...,Mailed Check,64.50,1888.45,0.00,0,79.20,1967.65,0,Competitor,Competitor had better devices
57,0098-BOWSO,0,26,0,0,San Jose,95131,37.387027,-121.897775,0,...,Bank Withdrawal,19.40,529.80,0.00,0,557.82,1087.62,0,Competitor,Competitor had better devices
58,0100-DUVFC,0,66,1,0,Wilmington,90744,33.782068,-118.262263,3,...,Bank Withdrawal,104.80,7308.95,6.11,0,2764.30,10067.14,0,Competitor,Competitor had better devices
59,0103-CSITQ,1,20,1,0,Modesto,95357,37.670526,-120.877572,10,...,Bank Withdrawal,109.40,6252.70,0.00,0,456.57,6709.27,0,Competitor,Competitor had better devices
60,0104-PPXDV,0,61,1,0,San Diego,92113,32.697098,-117.116587,10,...,Credit Card,50.30,2878.55,10.23,0,1065.46,3933.78,0,Competitor,Competitor had better devices
61,0106-GHRQR,0,24,0,0,Rancho Palos Verdes,90275,33.753146,-118.367459,0,...,Bank Withdrawal,71.40,1212.10,0.00,0,411.36,1623.46,0,Competitor,Competitor had better devices
62,0106-UGRDO,1,55,1,0,Kenwood,95452,38.419525,-122.521585,3,...,Bank Withdrawal,116.00,8182.85,0.00,0,2657.88,10840.73,0,Competitor,Competitor had better devices
63,0107-WESLM,0,32,0,0,West Point,95255,38.419350,-120.469545,0,...,Bank Withdrawal,19.85,19.85,0.00,0,31.77,51.62,1,Attitude,Attitude of support person
64,0107-YHINA,0,59,0,0,Los Angeles,90062,34.003553,-118.308933,0,...,Bank Withdrawal,99.75,99.75,0.00,0,40.71,140.46,1,Competitor,Competitor had better devices
65,0111-KLBQG,0,71,1,1,Morongo Valley,92256,34.097863,-116.594561,9,...,Mailed Check,93.95,2861.45,0.00,0,1019.52,3880.97,0,Competitor,Competitor had better devices
66,0112-QAWRZ,0,49,1,2,Palo Verde,92266,33.324900,-114.758334,8,...,Bank Withdrawal,90.80,1442.20,0.00,0,779.36,2221.56,0,Competitor,Competitor had better devices
67,0112-QWPNC,0,61,1,0,Valyermo,93563,34.395830,-117.734568,1,...,Bank Withdrawal,84.35,4059.35,0.00,0,1937.95,5997.30,1,Competitor,Competitor offered higher download speeds
68,0114-IGABW,1,40,1,0,Cambria,93428,35.591387,-121.032256,2,...,Bank Withdrawal,58.25,4145.90,0.00,0,0.00,4145.90,0,Competitor,Competitor had better devices
69,0114-PEGZZ,1,39,0,0,Round Mountain,96084,40.923558,-122.059933,0,...,Bank Withdrawal,107.55,3645.50,0.00,0,1639.77,5285.27,0,Competitor,Competitor had better devices
70,0114-RSRRW,1,21,1,0,Klamath,95548,41.572813,-124.035011,9,...,Bank Withdrawal,19.95,187.75,0.00,0,496.00,683.75,0,Competitor,Competitor had better devices
71,0115-TFERT,0,24,1,0,Fresno,93650,36.841655,-119.797113,1,...,Bank Withdrawal,111.20,2317.10,0.00,120,761.46,3198.56,1,Attitude,Attitude of service provider
72,0117-LFRMW,0,52,1,1,Angwin,94508,38.542448,-122.419923,1,...,Bank Withdrawal,40.20,1448.80,0.00,0,0.00,1448.80,1,Competitor,Competitor offered more data
73,0118-JPNOY,1,71,0,0,Le Grand,95333,37.249377,-120.249581,0,...,Credit Card,85.80,2193.65,0.00,0,877.24,3070.89,0,Competitor,Competitor had better devices
74,0121-SNYRK,0,45,0,0,Redway,95560,40.142256,-123.852927,0,...,Credit Card,35.40,1748.90,0.00,0,0.00,1748.90,0,Competitor,Competitor had better devices
75,0122-OAHPZ,1,29,0,0,San Diego,92122,32.857230,-117.209774,0,...,Bank Withdrawal,73.85,511.25,13.03,0,200.34,698.56,1,Competitor,Competitor made better offer
76,0123-CRBRT,1,62,1,0,Monterey Park,91755,34.049172,-118.115022,1,...,Mailed Check,88.10,5526.75,0.00,0,2878.59,8405.34,0,Competitor,Competitor had better devices
77,0125-LZQXK,0,42,0,0,Big Oak Flat,95305,37.818589,-120.256995,0,...,Bank Withdrawal,101.35,1553.95,0.00,0,688.80,2242.75,1,Attitude,Attitude of service provider

In [639]:
tel_df.drop_duplicates()

,Customer ID,Gender,Age,Married,Number of Dependents,City,Zip Code,Latitude,Longitude,Number of Referrals,...,Payment Method,Monthly Charge,Total Charges,Total Refunds,Total Extra Data Charges,Total Long Distance Charges,Total Revenue,Customer Status,Churn Category,Churn Reason
25,0032-PGELS,1,37,1,1,Palomar Mountain,92060,33.309852,-116.823091,1,...,Bank Withdrawal,30.50,30.50,0.00,0,0.00,30.50,1,Attitude,Attitude of service provider
26,0036-IHMOT,1,37,1,3,Parlier,93648,36.622237,-119.521126,10,...,Bank Withdrawal,103.70,5656.75,0.00,20,1927.20,7603.95,0,Competitor,Competitor had better devices
27,0040-HALCW,0,42,1,3,Modesto,95358,37.612612,-121.108568,3,...,Credit Card,20.40,1090.60,0.00,0,1063.80,2154.40,0,Competitor,Competitor had better devices
28,0042-JVWOJ,0,64,0,0,Glen Ellen,95442,38.368744,-122.522642,0,...,Bank Withdrawal,19.60,471.85,21.25,0,980.20,1430.80,0,Competitor,Competitor had better devices
29,0042-RLHYP,1,47,1,3,Eureka,95503,40.737431,-124.108897,5,...,Bank Withdrawal,19.70,1396.90,0.00,0,2648.91,4045.81,0,Competitor,Competitor had better devices
30,0048-LUMLS,0,23,1,3,Moss Beach,94038,37.515556,-122.502311,1,...,Credit Card,91.20,3247.55,0.00,0,1591.37,4838.92,0,Competitor,Competitor had better devices
31,0048-PIHNL,1,48,1,0,Los Angeles,90058,34.001617,-118.222274,5,...,Bank Withdrawal,20.45,900.90,0.00,0,2429.42,3330.32,0,Competitor,Competitor had better devices
32,0052-DCKON,0,28,1,0,Los Angeles,90063,34.044271,-118.185237,9,...,Bank Withdrawal,-2.00,7942.15,0.00,0,2888.82,10830.97,0,Competitor,Competitor had better devices
33,0052-YNYOT,1,28,0,0,Calexico,92231,32.690654,-115.431225,0,...,Bank Withdrawal,20.55,1343.40,30.53,0,1549.04,2861.91,0,Competitor,Competitor had better devices
34,0056-EPFBG,0,33,1,1,Redding,96003,40.677649,-122.294670,4,...,Credit Card,39.40,825.40,0.00,0,0.00,825.40,0,Competitor,Competitor had better devices
35,0057-QBUQH,1,31,0,3,San Martin,95046,37.084697,-121.606417,0,...,Bank Withdrawal,25.10,1070.15,0.00,0,1317.52,2387.67,0,Competitor,Competitor had better devices
36,0058-EVZWM,1,37,1,0,Stockton,95209,38.044523,-121.348048,2,...,Bank Withdrawal,89.80,4959.60,0.00,0,279.40,5239.00,0,Competitor,Competitor had better devices
37,0060-FUALY,1,60,1,0,Los Angeles,90003,33.964131,-118.272783,4,...,Bank Withdrawal,94.75,5597.65,0.00,0,967.01,6564.66,0,Competitor,Competitor had better devices
38,0064-SUDOG,1,48,1,3,Huntington Park,90255,33.978030,-118.217141,3,...,Bank Withdrawal,20.30,224.50,0.00,0,231.36,455.86,0,Competitor,Competitor had better devices
39,0064-YIJGF,0,60,1,3,Yermo,92398,35.013299,-116.834092,7,...,Bank Withdrawal,75.75,1929.00,0.00,0,682.02,2611.02,0,Competitor,Competitor had better devices
40,0067-DKWBL,0,69,0,0,San Diego,92129,32.961064,-117.134917,0,...,Bank Withdrawal,49.25,91.10,0.00,0,87.98,179.08,1,Competitor,Competitor made better offer
41,0068-FIGTF,1,20,0,0,Fremont,94539,37.516791,-121.899117,0,...,Credit Card,78.20,2078.95,0.00,0,1320.57,3399.52,0,Competitor,Competitor had better devices
42,0071-NDAFP,0,31,1,3,Santa Rosa,95405,38.439696,-122.668817,1,...,Credit Card,25.50,630.60,44.42,0,592.25,1178.43,0,Competitor,Competitor had better devices
43,0074-HDKDG,0,46,1,0,San Jose,95126,37.327069,-121.916819,5,...,Bank Withdrawal,61.60,1611.00,44.90,0,161.25,1727.35,0,Competitor,Competitor had better devices
44,0076-LVEPS,0,57,0,1,Tujunga,91042,34.296574,-118.244839,0,...,Credit Card,45.00,1242.45,12.26,0,0.00,1230.19,0,Competitor,Competitor had better devices
45,0078-XZMHT,0,19,1,0,Visalia,93291,36.391777,-119.372842,5,...,Bank Withdrawal,85.15,6316.20,0.00,0,2329.92,8646.12,0,Competitor,Competitor had better devices
46,0080-EMYVY,1,64,0,0,Lodi,95240,38.123544,-121.159078,0,...,Credit Card,51.45,727.85,0.00,0,336.56,1064.41,0,Competitor,Competitor had better devices
47,0080-OROZO,1,38,0,0,El Portal,95318,37.654551,-119.822984,0,...,Bank Withdrawal,99.25,3532.00,0.00,0,1274.70,4806.70,0,Competitor,Competitor had better devices
48,0082-LDZUE,0,54,0,0,Calistoga,94515,38.629618,-122.593216,0,...,Credit Card,44.30,44.30,0.00,0,42.95,87.25,0,Competitor,Competitor had better devices
49,0082-OQIQY,0,50,0,0,Farmington,95230,37.956963,-120.863055,0,...,Bank Withdrawal,94.20,2607.60,0.00,20,59.45,2687.05,0,Competitor,Competitor had better devices
50,0083-PIVIK,0,25,0,0,Tulelake,96134,41.813521,-121.492666,0,...,Bank Withdrawal,81.25,5567.55,0.00,40,351.36,5958.91,0,Competitor,Competitor had better devices
51,0089-IIQKO,1,35,1,3,Coleville,96107,38.425280,-119.475741,1,...,Credit Card,99.95,3767.40,0.00,0,950.82,4718.22,0,Competitor,Competitor had better devices
52,0093-EXYQL,1,72,0,0,Ojai,93023,34.581308,-118.931948,0,...,Bank Withdrawal,91.55,3673.60,0.00,0,1765.60,5439.20,0,Competitor,Competitor had better devices
53,0093-XWZFY,0,51,0,0,Desert Hot Springs,92241,33.832799,-116.250973,0,...,Credit Card,104.50,4036.85,0.00,0,1507.60,5544.45,1,Competitor,Competitor had better devices
54,0094-OIFMO,1,78,0,1,North Hollywood,91605,34.207295,-118.400022,0,...,Bank Withdrawal,95.00,1120.30,0.00,120,127.49,1367.79,1,Dissatisfaction,Product dissatisfaction
55,0096-BXERS,1,30,1,0,Inverness,94937,38.099323,-122.945723,10,...,Bank Withdrawal,50.35,314.55,0.00,0,255.96,570.51,0,Competitor,Competitor had better devices
56,0096-FCPUF,0,58,0,0,Santa Rosa,95404,38.526941,-122.709096,0,...,Mailed Check,64.50,1888.45,0.00,0,79.20,1967.65,0,Competitor,Competitor had better devices
57,0098-BOWSO,0,26,0,0,San Jose,95131,37.387027,-121.897775,0,...,Bank Withdrawal,19.40,529.80,0.00,0,557.82,1087.62,0,Competitor,Competitor had better devices
58,0100-DUVFC,0,66,1,0,Wilmington,90744,33.782068,-118.262263,3,...,Bank Withdrawal,104.80,7308.95,6.11,0,2764.30,10067.14,0,Competitor,Competitor had better devices
59,0103-CSITQ,1,20,1,0,Modesto,95357,37.670526,-120.877572,10,...,Bank Withdrawal,109.40,6252.70,0.00,0,456.57,6709.27,0,Competitor,Competitor had better devices
60,0104-PPXDV,0,61,1,0,San Diego,92113,32.697098,-117.116587,10,...,Credit Card,50.30,2878.55,10.23,0,1065.46,3933.78,0,Competitor,Competitor had better devices
61,0106-GHRQR,0,24,0,0,Rancho Palos Verdes,90275,33.753146,-118.367459,0,...,Bank Withdrawal,71.40,1212.10,0.00,0,411.36,1623.46,0,Competitor,Competitor had better devices
62,0106-UGRDO,1,55,1,0,Kenwood,95452,38.419525,-122.521585,3,...,Bank Withdrawal,116.00,8182.85,0.00,0,2657.88,10840.73,0,Competitor,Competitor had better devices
63,0107-WESLM,0,32,0,0,West Point,95255,38.419350,-120.469545,0,...,Bank Withdrawal,19.85,19.85,0.00,0,31.77,51.62,1,Attitude,Attitude of support person
64,0107-YHINA,0,59,0,0,Los Angeles,90062,34.003553,-118.308933,0,...,Bank Withdrawal,99.75,99.75,0.00,0,40.71,140.46,1,Competitor,Competitor had better devices
65,0111-KLBQG,0,71,1,1,Morongo Valley,92256,34.097863,-116.594561,9,...,Mailed Check,93.95,2861.45,0.00,0,1019.52,3880.97,0,Competitor,Competitor had better devices
66,0112-QAWRZ,0,49,1,2,Palo Verde,92266,33.324900,-114.758334,8,...,Bank Withdrawal,90.80,1442.20,0.00,0,779.36,2221.56,0,Competitor,Competitor had better devices
67,0112-QWPNC,0,61,1,0,Valyermo,93563,34.395830,-117.734568,1,...,Bank Withdrawal,84.35,4059.35,0.00,0,1937.95,5997.30,1,Competitor,Competitor offered higher download speeds
68,0114-IGABW,1,40,1,0,Cambria,93428,35.591387,-121.032256,2,...,Bank Withdrawal,58.25,4145.90,0.00,0,0.00,4145.90,0,Competitor,Competitor had better devices
69,0114-PEGZZ,1,39,0,0,Round Mountain,96084,40.923558,-122.059933,0,...,Bank Withdrawal,107.55,3645.50,0.00,0,1639.77,5285.27,0,Competitor,Competitor had better devices
70,0114-RSRRW,1,21,1,0,Klamath,95548,41.572813,-124.035011,9,...,Bank Withdrawal,19.95,187.75,0.00,0,496.00,683.75,0,Competitor,Competitor had better devices
71,0115-TFERT,0,24,1,0,Fresno,93650,36.841655,-119.797113,1,...,Bank Withdrawal,111.20,2317.10,0.00,120,761.46,3198.56,1,Attitude,Attitude of service provider
72,0117-LFRMW,0,52,1,1,Angwin,94508,38.542448,-122.419923,1,...,Bank Withdrawal,40.20,1448.80,0.00,0,0.00,1448.80,1,Competitor,Competitor offered more data
73,0118-JPNOY,1,71,0,0,Le Grand,95333,37.249377,-120.249581,0,...,Credit Card,85.80,2193.65,0.00,0,877.24,3070.89,0,Competitor,Competitor had better devices
74,0121-SNYRK,0,45,0,0,Redway,95560,40.142256,-123.852927,0,...,Credit Card,35.40,1748.90,0.00,0,0.00,1748.90,0,Competitor,Competitor had better devices
75,0122-OAHPZ,1,29,0,0,San Diego,92122,32.857230,-117.209774,0,...,Bank Withdrawal,73.85,511.25,13.03,0,200.34,698.56,1,Competitor,Competitor made better offer
76,0123-CRBRT,1,62,1,0,Monterey Park,91755,34.049172,-118.115022,1,...,Mailed Check,88.10,5526.75,0.00,0,2878.59,8405.34,0,Competitor,Competitor had better devices
77,0125-LZQXK,0,42,0,0,Big Oak Flat,95305,37.818589,-120.256995,0,...,Bank Withdrawal,101.35,1553.95,0.00,0,688.80,2242.75,1,Attitude,Attitude of service provider

In [640]:
tel_df.drop_duplicates(keep='last')

,Customer ID,Gender,Age,Married,Number of Dependents,City,Zip Code,Latitude,Longitude,Number of Referrals,...,Payment Method,Monthly Charge,Total Charges,Total Refunds,Total Extra Data Charges,Total Long Distance Charges,Total Revenue,Customer Status,Churn Category,Churn Reason
25,0032-PGELS,1,37,1,1,Palomar Mountain,92060,33.309852,-116.823091,1,...,Bank Withdrawal,30.50,30.50,0.00,0,0.00,30.50,1,Attitude,Attitude of service provider
26,0036-IHMOT,1,37,1,3,Parlier,93648,36.622237,-119.521126,10,...,Bank Withdrawal,103.70,5656.75,0.00,20,1927.20,7603.95,0,Competitor,Competitor had better devices
27,0040-HALCW,0,42,1,3,Modesto,95358,37.612612,-121.108568,3,...,Credit Card,20.40,1090.60,0.00,0,1063.80,2154.40,0,Competitor,Competitor had better devices
28,0042-JVWOJ,0,64,0,0,Glen Ellen,95442,38.368744,-122.522642,0,...,Bank Withdrawal,19.60,471.85,21.25,0,980.20,1430.80,0,Competitor,Competitor had better devices
29,0042-RLHYP,1,47,1,3,Eureka,95503,40.737431,-124.108897,5,...,Bank Withdrawal,19.70,1396.90,0.00,0,2648.91,4045.81,0,Competitor,Competitor had better devices
30,0048-LUMLS,0,23,1,3,Moss Beach,94038,37.515556,-122.502311,1,...,Credit Card,91.20,3247.55,0.00,0,1591.37,4838.92,0,Competitor,Competitor had better devices
31,0048-PIHNL,1,48,1,0,Los Angeles,90058,34.001617,-118.222274,5,...,Bank Withdrawal,20.45,900.90,0.00,0,2429.42,3330.32,0,Competitor,Competitor had better devices
32,0052-DCKON,0,28,1,0,Los Angeles,90063,34.044271,-118.185237,9,...,Bank Withdrawal,-2.00,7942.15,0.00,0,2888.82,10830.97,0,Competitor,Competitor had better devices
33,0052-YNYOT,1,28,0,0,Calexico,92231,32.690654,-115.431225,0,...,Bank Withdrawal,20.55,1343.40,30.53,0,1549.04,2861.91,0,Competitor,Competitor had better devices
34,0056-EPFBG,0,33,1,1,Redding,96003,40.677649,-122.294670,4,...,Credit Card,39.40,825.40,0.00,0,0.00,825.40,0,Competitor,Competitor had better devices
35,0057-QBUQH,1,31,0,3,San Martin,95046,37.084697,-121.606417,0,...,Bank Withdrawal,25.10,1070.15,0.00,0,1317.52,2387.67,0,Competitor,Competitor had better devices
36,0058-EVZWM,1,37,1,0,Stockton,95209,38.044523,-121.348048,2,...,Bank Withdrawal,89.80,4959.60,0.00,0,279.40,5239.00,0,Competitor,Competitor had better devices
37,0060-FUALY,1,60,1,0,Los Angeles,90003,33.964131,-118.272783,4,...,Bank Withdrawal,94.75,5597.65,0.00,0,967.01,6564.66,0,Competitor,Competitor had better devices
38,0064-SUDOG,1,48,1,3,Huntington Park,90255,33.978030,-118.217141,3,...,Bank Withdrawal,20.30,224.50,0.00,0,231.36,455.86,0,Competitor,Competitor had better devices
39,0064-YIJGF,0,60,1,3,Yermo,92398,35.013299,-116.834092,7,...,Bank Withdrawal,75.75,1929.00,0.00,0,682.02,2611.02,0,Competitor,Competitor had better devices
40,0067-DKWBL,0,69,0,0,San Diego,92129,32.961064,-117.134917,0,...,Bank Withdrawal,49.25,91.10,0.00,0,87.98,179.08,1,Competitor,Competitor made better offer
41,0068-FIGTF,1,20,0,0,Fremont,94539,37.516791,-121.899117,0,...,Credit Card,78.20,2078.95,0.00,0,1320.57,3399.52,0,Competitor,Competitor had better devices
42,0071-NDAFP,0,31,1,3,Santa Rosa,95405,38.439696,-122.668817,1,...,Credit Card,25.50,630.60,44.42,0,592.25,1178.43,0,Competitor,Competitor had better devices
43,0074-HDKDG,0,46,1,0,San Jose,95126,37.327069,-121.916819,5,...,Bank Withdrawal,61.60,1611.00,44.90,0,161.25,1727.35,0,Competitor,Competitor had better devices
44,0076-LVEPS,0,57,0,1,Tujunga,91042,34.296574,-118.244839,0,...,Credit Card,45.00,1242.45,12.26,0,0.00,1230.19,0,Competitor,Competitor had better devices
45,0078-XZMHT,0,19,1,0,Visalia,93291,36.391777,-119.372842,5,...,Bank Withdrawal,85.15,6316.20,0.00,0,2329.92,8646.12,0,Competitor,Competitor had better devices
46,0080-EMYVY,1,64,0,0,Lodi,95240,38.123544,-121.159078,0,...,Credit Card,51.45,727.85,0.00,0,336.56,1064.41,0,Competitor,Competitor had better devices
47,0080-OROZO,1,38,0,0,El Portal,95318,37.654551,-119.822984,0,...,Bank Withdrawal,99.25,3532.00,0.00,0,1274.70,4806.70,0,Competitor,Competitor had better devices
48,0082-LDZUE,0,54,0,0,Calistoga,94515,38.629618,-122.593216,0,...,Credit Card,44.30,44.30,0.00,0,42.95,87.25,0,Competitor,Competitor had better devices
49,0082-OQIQY,0,50,0,0,Farmington,95230,37.956963,-120.863055,0,...,Bank Withdrawal,94.20,2607.60,0.00,20,59.45,2687.05,0,Competitor,Competitor had better devices
50,0083-PIVIK,0,25,0,0,Tulelake,96134,41.813521,-121.492666,0,...,Bank Withdrawal,81.25,5567.55,0.00,40,351.36,5958.91,0,Competitor,Competitor had better devices
51,0089-IIQKO,1,35,1,3,Coleville,96107,38.425280,-119.475741,1,...,Credit Card,99.95,3767.40,0.00,0,950.82,4718.22,0,Competitor,Competitor had better devices
52,0093-EXYQL,1,72,0,0,Ojai,93023,34.581308,-118.931948,0,...,Bank Withdrawal,91.55,3673.60,0.00,0,1765.60,5439.20,0,Competitor,Competitor had better devices
53,0093-XWZFY,0,51,0,0,Desert Hot Springs,92241,33.832799,-116.250973,0,...,Credit Card,104.50,4036.85,0.00,0,1507.60,5544.45,1,Competitor,Competitor had better devices
54,0094-OIFMO,1,78,0,1,North Hollywood,91605,34.207295,-118.400022,0,...,Bank Withdrawal,95.00,1120.30,0.00,120,127.49,1367.79,1,Dissatisfaction,Product dissatisfaction
55,0096-BXERS,1,30,1,0,Inverness,94937,38.099323,-122.945723,10,...,Bank Withdrawal,50.35,314.55,0.00,0,255.96,570.51,0,Competitor,Competitor had better devices
56,0096-FCPUF,0,58,0,0,Santa Rosa,95404,38.526941,-122.709096,0,...,Mailed Check,64.50,1888.45,0.00,0,79.20,1967.65,0,Competitor,Competitor had better devices
57,0098-BOWSO,0,26,0,0,San Jose,95131,37.387027,-121.897775,0,...,Bank Withdrawal,19.40,529.80,0.00,0,557.82,1087.62,0,Competitor,Competitor had better devices
58,0100-DUVFC,0,66,1,0,Wilmington,90744,33.782068,-118.262263,3,...,Bank Withdrawal,104.80,7308.95,6.11,0,2764.30,10067.14,0,Competitor,Competitor had better devices
59,0103-CSITQ,1,20,1,0,Modesto,95357,37.670526,-120.877572,10,...,Bank Withdrawal,109.40,6252.70,0.00,0,456.57,6709.27,0,Competitor,Competitor had better devices
60,0104-PPXDV,0,61,1,0,San Diego,92113,32.697098,-117.116587,10,...,Credit Card,50.30,2878.55,10.23,0,1065.46,3933.78,0,Competitor,Competitor had better devices
61,0106-GHRQR,0,24,0,0,Rancho Palos Verdes,90275,33.753146,-118.367459,0,...,Bank Withdrawal,71.40,1212.10,0.00,0,411.36,1623.46,0,Competitor,Competitor had better devices
62,0106-UGRDO,1,55,1,0,Kenwood,95452,38.419525,-122.521585,3,...,Bank Withdrawal,116.00,8182.85,0.00,0,2657.88,10840.73,0,Competitor,Competitor had better devices
63,0107-WESLM,0,32,0,0,West Point,95255,38.419350,-120.469545,0,...,Bank Withdrawal,19.85,19.85,0.00,0,31.77,51.62,1,Attitude,Attitude of support person
64,0107-YHINA,0,59,0,0,Los Angeles,90062,34.003553,-118.308933,0,...,Bank Withdrawal,99.75,99.75,0.00,0,40.71,140.46,1,Competitor,Competitor had better devices
65,0111-KLBQG,0,71,1,1,Morongo Valley,92256,34.097863,-116.594561,9,...,Mailed Check,93.95,2861.45,0.00,0,1019.52,3880.97,0,Competitor,Competitor had better devices
66,0112-QAWRZ,0,49,1,2,Palo Verde,92266,33.324900,-114.758334,8,...,Bank Withdrawal,90.80,1442.20,0.00,0,779.36,2221.56,0,Competitor,Competitor had better devices
67,0112-QWPNC,0,61,1,0,Valyermo,93563,34.395830,-117.734568,1,...,Bank Withdrawal,84.35,4059.35,0.00,0,1937.95,5997.30,1,Competitor,Competitor offered higher download speeds
68,0114-IGABW,1,40,1,0,Cambria,93428,35.591387,-121.032256,2,...,Bank Withdrawal,58.25,4145.90,0.00,0,0.00,4145.90,0,Competitor,Competitor had better devices
69,0114-PEGZZ,1,39,0,0,Round Mountain,96084,40.923558,-122.059933,0,...,Bank Withdrawal,107.55,3645.50,0.00,0,1639.77,5285.27,0,Competitor,Competitor had better devices
70,0114-RSRRW,1,21,1,0,Klamath,95548,41.572813,-124.035011,9,...,Bank Withdrawal,19.95,187.75,0.00,0,496.00,683.75,0,Competitor,Competitor had better devices
71,0115-TFERT,0,24,1,0,Fresno,93650,36.841655,-119.797113,1,...,Bank Withdrawal,111.20,2317.10,0.00,120,761.46,3198.56,1,Attitude,Attitude of service provider
72,0117-LFRMW,0,52,1,1,Angwin,94508,38.542448,-122.419923,1,...,Bank Withdrawal,40.20,1448.80,0.00,0,0.00,1448.80,1,Competitor,Competitor offered more data
73,0118-JPNOY,1,71,0,0,Le Grand,95333,37.249377,-120.249581,0,...,Credit Card,85.80,2193.65,0.00,0,877.24,3070.89,0,Competitor,Competitor had better devices
74,0121-SNYRK,0,45,0,0,Redway,95560,40.142256,-123.852927,0,...,Credit Card,35.40,1748.90,0.00,0,0.00,1748.90,0,Competitor,Competitor had better devices
75,0122-OAHPZ,1,29,0,0,San Diego,92122,32.857230,-117.209774,0,...,Bank Withdrawal,73.85,511.25,13.03,0,200.34,698.56,1,Competitor,Competitor made better offer
76,0123-CRBRT,1,62,1,0,Monterey Park,91755,34.049172,-118.115022,1,...,Mailed Check,88.10,5526.75,0.00,0,2878.59,8405.34,0,Competitor,Competitor had better devices
77,0125-LZQXK,0,42,0,0,Big Oak Flat,95305,37.818589,-120.256995,0,...,Bank Withdrawal,101.35,1553.95,0.00,0,688.80,2242.75,1,Attitude,Attitude of service provider

In [641]:
tel_df.drop_duplicates(subset=['Gender'])

,Customer ID,Gender,Age,Married,Number of Dependents,City,Zip Code,Latitude,Longitude,Number of Referrals,...,Payment Method,Monthly Charge,Total Charges,Total Refunds,Total Extra Data Charges,Total Long Distance Charges,Total Revenue,Customer Status,Churn Category,Churn Reason
25,0032-PGELS,1,37,1,1,Palomar Mountain,92060,33.309852,-116.823091,1,...,Bank Withdrawal,30.5,30.5,0.0,0,0.0,30.5,1,Attitude,Attitude of service provider
27,0040-HALCW,0,42,1,3,Modesto,95358,37.612612,-121.108568,3,...,Credit Card,20.4,1090.6,0.0,0,1063.8,2154.4,0,Competitor,Competitor had better devices

In [642]:
df["Longitude"].astype('float32')

0      -118.999069
1      -118.203873
2      -117.922615
3      -122.115433
4      -119.079903
           ...
7038   -116.997261
7039   -120.954269
7040   -123.645119
7041   -117.263626
7042   -120.636360
Name: Longitude, Length: 7043, dtype: float32

In [643]:
df['Zip Code']=df['Zip Code'].astype(float)
df['Zip Code'].mean()

93486.07056651995

In [644]:
df['Zip Code'].unique()

array([93225., 91206., 92627., ..., 91934., 93013., 95956.])

In [645]:
df["Zip Code"].median()

93518.0

In [646]:
df.duplicated().sum()

0

In [647]:
df.drop_duplicates(inplace=True)
df

,Customer ID,Gender,Age,Married,Number of Dependents,City,Zip Code,Latitude,Longitude,Number of Referrals,...,Payment Method,Monthly Charge,Total Charges,Total Refunds,Total Extra Data Charges,Total Long Distance Charges,Total Revenue,Customer Status,Churn Category,Churn Reason
0,0002-ORFBO,1,37,1,0,Frazier Park,93225.0,34.827662,-118.999073,2,...,Credit Card,65.60,593.30,0.00,0,381.51,974.81,0,Competitor,Competitor had better devices
1,0003-MKNFE,0,46,0,0,Glendale,91206.0,34.162515,-118.203869,0,...,Credit Card,-4.00,542.40,38.33,10,96.21,610.28,0,Competitor,Competitor had better devices
2,0004-TLHLJ,0,50,0,0,Costa Mesa,92627.0,33.645672,-117.922613,0,...,Bank Withdrawal,73.90,280.85,0.00,0,134.60,415.45,1,Competitor,Competitor had better devices
3,0011-IGKFF,0,78,1,0,Martinez,94553.0,38.014457,-122.115432,1,...,Bank Withdrawal,98.00,1237.85,0.00,0,361.66,1599.51,1,Dissatisfaction,Product dissatisfaction
4,0013-EXCHZ,1,75,1,0,Camarillo,93010.0,34.227846,-119.079903,3,...,Credit Card,83.90,267.40,0.00,0,22.14,289.54,1,Dissatisfaction,Network reliability
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,9987-LUTYD,1,20,0,0,La Mesa,91941.0,32.759327,-116.997260,0,...,Credit Card,55.15,742.90,0.00,0,606.84,1349.74,0,Competitor,Competitor had better devices
7039,9992-RRAMN,0,40,1,0,Riverbank,95367.0,37.734971,-120.954271,1,...,Bank Withdrawal,85.10,1873.70,0.00,0,356.40,2230.10,1,Dissatisfaction,Product dissatisfaction
7040,9992-UJOEL,0,22,0,0,Elk,95432.0,39.108252,-123.645121,0,...,Credit Card,50.30,92.75,0.00,0,37.24,129.99,0,Competitor,Competitor had better devices
7041,9993-LHIEB,0,21,1,0,Solana Beach,92075.0,33.001813,-117.263628,5,...,Credit Card,67.85,4627.65,0.00,0,142.04,4769.69,0,Competitor,Competitor had better devices
7042,9995-HOTOH,0,36,1,0,Sierra City,96125.0,39.600599,-120.636358,1,...,Bank Withdrawal,59.00,3707.60,0.00,0,0.00,3707.60,0,Competitor,Competitor had better devices

In [648]:
df['Gender'] = pd.to_numeric(df['Gender'], errors='coerce')
df

,Customer ID,Gender,Age,Married,Number of Dependents,City,Zip Code,Latitude,Longitude,Number of Referrals,...,Payment Method,Monthly Charge,Total Charges,Total Refunds,Total Extra Data Charges,Total Long Distance Charges,Total Revenue,Customer Status,Churn Category,Churn Reason
0,0002-ORFBO,1,37,1,0,Frazier Park,93225.0,34.827662,-118.999073,2,...,Credit Card,65.60,593.30,0.00,0,381.51,974.81,0,Competitor,Competitor had better devices
1,0003-MKNFE,0,46,0,0,Glendale,91206.0,34.162515,-118.203869,0,...,Credit Card,-4.00,542.40,38.33,10,96.21,610.28,0,Competitor,Competitor had better devices
2,0004-TLHLJ,0,50,0,0,Costa Mesa,92627.0,33.645672,-117.922613,0,...,Bank Withdrawal,73.90,280.85,0.00,0,134.60,415.45,1,Competitor,Competitor had better devices
3,0011-IGKFF,0,78,1,0,Martinez,94553.0,38.014457,-122.115432,1,...,Bank Withdrawal,98.00,1237.85,0.00,0,361.66,1599.51,1,Dissatisfaction,Product dissatisfaction
4,0013-EXCHZ,1,75,1,0,Camarillo,93010.0,34.227846,-119.079903,3,...,Credit Card,83.90,267.40,0.00,0,22.14,289.54,1,Dissatisfaction,Network reliability
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,9987-LUTYD,1,20,0,0,La Mesa,91941.0,32.759327,-116.997260,0,...,Credit Card,55.15,742.90,0.00,0,606.84,1349.74,0,Competitor,Competitor had better devices
7039,9992-RRAMN,0,40,1,0,Riverbank,95367.0,37.734971,-120.954271,1,...,Bank Withdrawal,85.10,1873.70,0.00,0,356.40,2230.10,1,Dissatisfaction,Product dissatisfaction
7040,9992-UJOEL,0,22,0,0,Elk,95432.0,39.108252,-123.645121,0,...,Credit Card,50.30,92.75,0.00,0,37.24,129.99,0,Competitor,Competitor had better devices
7041,9993-LHIEB,0,21,1,0,Solana Beach,92075.0,33.001813,-117.263628,5,...,Credit Card,67.85,4627.65,0.00,0,142.04,4769.69,0,Competitor,Competitor had better devices
7042,9995-HOTOH,0,36,1,0,Sierra City,96125.0,39.600599,-120.636358,1,...,Bank Withdrawal,59.00,3707.60,0.00,0,0.00,3707.60,0,Competitor,Competitor had better devices

REMOVING UNWANTED COLUMNS

In [649]:
df.drop(columns=['Internet Type','Churn Category','Churn Reason','Customer ID','City','Offer'], inplace=True)

In [650]:
df

,Gender,Age,Married,Number of Dependents,Zip Code,Latitude,Longitude,Number of Referrals,Tenure in Months,Phone Service,...,Contract,Paperless Billing,Payment Method,Monthly Charge,Total Charges,Total Refunds,Total Extra Data Charges,Total Long Distance Charges,Total Revenue,Customer Status
0,1,37,1,0,93225.0,34.827662,-118.999073,2,9,1,...,One Year,1,Credit Card,65.60,593.30,0.00,0,381.51,974.81,0
1,0,46,0,0,91206.0,34.162515,-118.203869,0,9,1,...,Month-to-Month,0,Credit Card,-4.00,542.40,38.33,10,96.21,610.28,0
2,0,50,0,0,92627.0,33.645672,-117.922613,0,4,1,...,Month-to-Month,1,Bank Withdrawal,73.90,280.85,0.00,0,134.60,415.45,1
3,0,78,1,0,94553.0,38.014457,-122.115432,1,13,1,...,Month-to-Month,1,Bank Withdrawal,98.00,1237.85,0.00,0,361.66,1599.51,1
4,1,75,1,0,93010.0,34.227846,-119.079903,3,3,1,...,Month-to-Month,1,Credit Card,83.90,267.40,0.00,0,22.14,289.54,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,1,20,0,0,91941.0,32.759327,-116.997260,0,13,1,...,One Year,0,Credit Card,55.15,742.90,0.00,0,606.84,1349.74,0
7039,0,40,1,0,95367.0,37.734971,-120.954271,1,22,1,...,Month-to-Month,1,Bank Withdrawal,85.10,1873.70,0.00,0,356.40,2230.10,1
7040,0,22,0,0,95432.0,39.108252,-123.645121,0,2,1,...,Month-to-Month,1,Credit Card,50.30,92.75,0.00,0,37.24,129.99,0
7041,0,21,1,0,92075.0,33.001813,-117.263628,5,67,1,...,Two Year,0,Credit Card,67.85,4627.65,0.00,0,142.04,4769.69,0
7042,0,36,1,0,96125.0,39.600599,-120.636358,1,63,0,...,Two Year,0,Bank Withdrawal,59.00,3707.60,0.00,0,0.00,3707.60,0

In [651]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 32 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Gender                             7043 non-null   int64
 1   Age                                7043 non-null   int64
 2   Married                            7043 non-null   int64
 3   Number of Dependents               7043 non-null   int64
 4   Zip Code                           7043 non-null   float64
 5   Latitude                           7043 non-null   float64
 6   Longitude                          7043 non-null   float64
 7   Number of Referrals                7043 non-null   int64
 8   Tenure in Months                   7043 non-null   int64
 9   Phone Service                      7043 non-null   int64
 10  Avg Monthly Long Distance Charges  7043 non-null   float64
 11  Multiple Lines                     7043 non-null   float64
 12  Internet Service                   7043 non-null   int64
 13  Avg Monthly GB Download            7043 non-null   float64
 14  Online Security                    7043 non-null   float64
 15  Online Backup                      7043 non-null   float64
 16  Device Protection Plan             7043 non-null   float64
 17  Premium Tech Support               7043 non-null   float64
 18  Streaming TV                       7043 non-null   float64
 19  Streaming Movies                   7043 non-null   float64
 20  Streaming Music                    7043 non-null   float64
 21  Unlimited Data                     7043 non-null   float64
 22  Contract                           7043 non-null   object
 23  Paperless Billing                  7043 non-null   int64
 24  Payment Method                     7043 non-null   object
 25  Monthly Charge                     7043 non-null   float64
 26  Total Charges                      7043 non-null   float64
 27  Total Refunds                      7043 non-null   float64
 28  Total Extra Data Charges           7043 non-null   int64
 29  Total Long Distance Charges        7043 non-null   float64
 30  Total Revenue                      7043 non-null   float64
 31  Customer Status                    7043 non-null   int64
dtypes: float64(19), int64(11), object(2)
memory usage: 1.7+ MB

Remove Negative Values

In [652]:
df['Monthly Charge'] = df['Monthly Charge'].abs()
df['Monthly Charge']

0       65.60
1        4.00
2       73.90
3       98.00
4       83.90
        ...
7038    55.15
7039    85.10
7040    50.30
7041    67.85
7042    59.00
Name: Monthly Charge, Length: 7043, dtype: float64

*For converting all numeric columns into positive at a time*

In [653]:
#num_cols = df.select_dtypes(include=['int64','float64']).columns
#df[num_cols] = df[num_cols].abs()

FOR CHECKING HOW MANY NEGATIVE VALUES IN THE COLUMN

In [654]:
for col in df.select_dtypes(include=['int64','float64']).columns:
    neg_count = (df[col] < 0).sum()
    if neg_count > 0:
        print(col, "has", neg_count, "negative values")

Longitude has 7043 negative values

In [655]:
df

,Gender,Age,Married,Number of Dependents,Zip Code,Latitude,Longitude,Number of Referrals,Tenure in Months,Phone Service,...,Contract,Paperless Billing,Payment Method,Monthly Charge,Total Charges,Total Refunds,Total Extra Data Charges,Total Long Distance Charges,Total Revenue,Customer Status
0,1,37,1,0,93225.0,34.827662,-118.999073,2,9,1,...,One Year,1,Credit Card,65.60,593.30,0.00,0,381.51,974.81,0
1,0,46,0,0,91206.0,34.162515,-118.203869,0,9,1,...,Month-to-Month,0,Credit Card,4.00,542.40,38.33,10,96.21,610.28,0
2,0,50,0,0,92627.0,33.645672,-117.922613,0,4,1,...,Month-to-Month,1,Bank Withdrawal,73.90,280.85,0.00,0,134.60,415.45,1
3,0,78,1,0,94553.0,38.014457,-122.115432,1,13,1,...,Month-to-Month,1,Bank Withdrawal,98.00,1237.85,0.00,0,361.66,1599.51,1
4,1,75,1,0,93010.0,34.227846,-119.079903,3,3,1,...,Month-to-Month,1,Credit Card,83.90,267.40,0.00,0,22.14,289.54,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,1,20,0,0,91941.0,32.759327,-116.997260,0,13,1,...,One Year,0,Credit Card,55.15,742.90,0.00,0,606.84,1349.74,0
7039,0,40,1,0,95367.0,37.734971,-120.954271,1,22,1,...,Month-to-Month,1,Bank Withdrawal,85.10,1873.70,0.00,0,356.40,2230.10,1
7040,0,22,0,0,95432.0,39.108252,-123.645121,0,2,1,...,Month-to-Month,1,Credit Card,50.30,92.75,0.00,0,37.24,129.99,0
7041,0,21,1,0,92075.0,33.001813,-117.263628,5,67,1,...,Two Year,0,Credit Card,67.85,4627.65,0.00,0,142.04,4769.69,0
7042,0,36,1,0,96125.0,39.600599,-120.636358,1,63,0,...,Two Year,0,Bank Withdrawal,59.00,3707.60,0.00,0,0.00,3707.60,0

Data Formating

*covert to date*

In [656]:
#df["date"] = pd.to_datetime(df["date"])

convert to float

In [657]:
df["Avg Monthly GB Download"] = df["Avg Monthly GB Download"].astype(float)
df['Avg Monthly GB Download']

0       16.0
1       10.0
2       30.0
3        4.0
4       11.0
        ...
7038    59.0
7039    17.0
7040    51.0
7041    58.0
7042     5.0
Name: Avg Monthly GB Download, Length: 7043, dtype: float64

convert to int

In [658]:
df["Gender"] = df["Gender"].astype(int)

In [659]:
df['Online Security']=df['Online Security'].astype(int)

In [660]:
df['Online Backup']=df['Online Backup'].astype(int)

Standard Scalar

In [661]:
from sklearn.preprocessing import StandardScaler

cols_to_scale = [
    'Monthly Charge',
    'Total Charges',
   'Tenure in Months',
    'Avg Monthly Long Distance Charges',
    'Total Long Distance Charges',
    'Total Revenue'
]

scaler = StandardScaler()
df[cols_to_scale] = scaler.fit_transform(df[cols_to_scale])

NORMALIZATION (min-max)

In [662]:
#df["Monthly Charge"] = (df["Monthly Charge"] - df["Monthly Charge"].min()) / (df["Monthly Charge"].max() - df["Monthly Charge"].min())
#df["Monthly Charge"]
#df["Total Charges"] = (df["Total Charges"] - df["Total Charges"].min()) / (df["Total Charges"].max() - df["Total Charges"].min())
#df["Total Charges"]
#df["Tenure in Months"] = (df["Tenure in Months"] - df["Tenure in Months"].min()) / (df["Tenure in Months"].max() - df["Tenure in Months"].min())
#df["Tenure in Months"]

Binning

In [663]:
bins = [0, 18, 35, 60, 100]
labels = ["Child", "Young", "Adult", "Senior"]

df["age_group"] = pd.cut(df["Age"], bins=bins, labels=labels)

OUTLIERS HANDLING

->we are calculating lower limit  and upper limit..

->below lower limit and above upper limit is considerd as outlier..

->by using  IQR method(INTER QUARTILE RANGE).

In [664]:
Q1=df['Monthly Charge'].quantile(0.25)
Q3=df['Monthly Charge'].quantile(0.75)
IQR=Q3-Q1
lower=Q1-1.5*IQR
upper=Q3+1.5*IQR
outliers=df[(df["Monthly Charge"]<lower)|(df['Monthly Charge']>upper)]
print(len(outliers))

0

In [665]:
Q1=df['Total Charges'].quantile(0.25)
Q3=df['Total Charges'].quantile(0.75)
IQR=Q3-Q1
lower=Q1-1.5*IQR
upper=Q3+1.5*IQR
outliers=df[(df["Total Charges"]<lower)|(df['Total Charges']>upper)]
print(len(outliers))

0

indicator random variables is for text data into numeric format..

 By using one-hot encoding

In [666]:
df = pd.get_dummies(df, columns=['Payment Method','Contract'])

In [667]:
#binarycolumns=['Payment Method_Bank Withdrawal','Payment Method_Credit Card','Payment Method_Mailed Check','Customer Status_Churned','Customer Status_Joined','Customer Status_Stayed','Contract_Month-to-Month','Contract_One Year','Contract_Two Year']
#df[binarycolumns]=df[binarycolumns].replace({'True':1,'False':0})

In [668]:
dummy_cols=df.select_dtypes(bool).columns
df[dummy_cols]=df[dummy_cols].astype(int)

Feature Engineering

Avg Monthly spend

In [669]:
df["avg_monthly_spend"] = df["Total Charges"] / (df['Tenure in Months'] + 1)

spending charge

In [670]:
df["spend_change"] = df["Monthly Charge"] - df["avg_monthly_spend"]

expensive customer

In [671]:
df["high_bill"] = (df["Monthly Charge"] > df["Monthly Charge"].median()).astype(int)

ROUNDING FLOAT VALUE

In [672]:
df=df.round(2)

In [673]:
df

,Gender,Age,Married,Number of Dependents,Zip Code,Latitude,Longitude,Number of Referrals,Tenure in Months,Phone Service,...,age_group,Payment Method_Bank Withdrawal,Payment Method_Credit Card,Payment Method_Mailed Check,Contract_Month-to-Month,Contract_One Year,Contract_Two Year,avg_monthly_spend,spend_change,high_bill
0,1,37,1,0,93225.0,34.83,-119.00,2,-0.95,1,...,Adult,0,1,0,0,1,0,-15.84,15.90,0
1,0,46,0,0,91206.0,34.16,-118.20,0,-0.95,1,...,Adult,0,1,0,1,0,0,-16.32,14.38,0
2,0,50,0,0,92627.0,33.65,-117.92,0,-1.16,1,...,Adult,1,0,0,1,0,0,5.63,-5.30,1
3,0,78,1,0,94553.0,38.01,-122.12,1,-0.79,1,...,Senior,1,0,0,1,0,0,-2.19,3.30,1
4,1,75,1,0,93010.0,34.23,-119.08,3,-1.20,1,...,Senior,0,1,0,1,0,0,4.50,-3.85,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,1,20,0,0,91941.0,32.76,-117.00,0,-0.79,1,...,Young,0,1,0,0,1,0,-3.23,2.95,0
7039,0,40,1,0,95367.0,37.73,-120.95,1,-0.42,1,...,Adult,1,0,0,1,0,0,-0.31,1.00,1
7040,0,22,0,0,95432.0,39.11,-123.65,0,-1.24,1,...,Young,0,1,0,1,0,0,4.05,-4.49,0
7041,0,21,1,0,92075.0,33.00,-117.26,5,1.41,1,...,Young,0,1,0,0,0,1,0.43,-0.30,0
7042,0,36,1,0,96125.0,39.60,-120.64,1,1.25,0,...,Adult,1,0,0,0,0,1,0.28,-0.44,0

In [674]:
df.to_csv("cleaned.csv", index=False)