In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv("/home/user/Downloads/telecom_customer_churn.csv")

In [3]:
df.shape

(7043, 38)

In [4]:
df.columns

Index(['Customer ID', 'Gender', 'Age', 'Married', 'Number of Dependents',
       'City', 'Zip Code', 'Latitude', 'Longitude', 'Number of Referrals',
       'Tenure in Months', 'Offer', 'Phone Service',
       'Avg Monthly Long Distance Charges', 'Multiple Lines',
       'Internet Service', 'Internet Type', 'Avg Monthly GB Download',
       'Online Security', 'Online Backup', 'Device Protection Plan',
       'Premium Tech Support', 'Streaming TV', 'Streaming Movies',
       'Streaming Music', 'Unlimited Data', 'Contract', 'Paperless Billing',
       'Payment Method', 'Monthly Charge', 'Total Charges', 'Total Refunds',
       'Total Extra Data Charges', 'Total Long Distance Charges',
       'Total Revenue', 'Customer Status', 'Churn Category', 'Churn Reason'],
      dtype='object')

In [5]:
df.dtypes

Customer ID                           object
Gender                                object
Age                                    int64
Married                               object
Number of Dependents                   int64
City                                  object
Zip Code                               int64
Latitude                             float64
Longitude                            float64
Number of Referrals                    int64
Tenure in Months                       int64
Offer                                 object
Phone Service                         object
Avg Monthly Long Distance Charges    float64
Multiple Lines                        object
Internet Service                      object
Internet Type                         object
Avg Monthly GB Download              float64
Online Security                       object
Online Backup                         object
Device Protection Plan                object
Premium Tech Support                  object
Streaming TV                          object
Streaming Movies                      object
Streaming Music                       object
Unlimited Data                        object
Contract                              object
Paperless Billing                     object
Payment Method                        object
Monthly Charge                       float64
Total Charges                        float64
Total Refunds                        float64
Total Extra Data Charges               int64
Total Long Distance Charges          float64
Total Revenue                        float64
Customer Status                       object
Churn Category                        object
Churn Reason                          object
dtype: object

In [6]:
df.head()

,Customer ID,Gender,Age,Married,Number of Dependents,City,Zip Code,Latitude,Longitude,Number of Referrals,...,Payment Method,Monthly Charge,Total Charges,Total Refunds,Total Extra Data Charges,Total Long Distance Charges,Total Revenue,Customer Status,Churn Category,Churn Reason
0,0002-ORFBO,Female,37,Yes,0,Frazier Park,93225,34.827662,-118.999073,2,...,Credit Card,65.6,593.30,0.00,0,381.51,974.81,Stayed,NaN,NaN
1,0003-MKNFE,Male,46,No,0,Glendale,91206,34.162515,-118.203869,0,...,Credit Card,-4.0,542.40,38.33,10,96.21,610.28,Stayed,NaN,NaN
2,0004-TLHLJ,Male,50,No,0,Costa Mesa,92627,33.645672,-117.922613,0,...,Bank Withdrawal,73.9,280.85,0.00,0,134.60,415.45,Churned,Competitor,Competitor had better devices
3,0011-IGKFF,Male,78,Yes,0,Martinez,94553,38.014457,-122.115432,1,...,Bank Withdrawal,98.0,1237.85,0.00,0,361.66,1599.51,Churned,Dissatisfaction,Product dissatisfaction
4,0013-EXCHZ,Female,75,Yes,0,Camarillo,93010,34.227846,-119.079903,3,...,Credit Card,83.9,267.40,0.00,0,22.14,289.54,Churned,Dissatisfaction,Network reliability

In [7]:
df.head(10)

,Customer ID,Gender,Age,Married,Number of Dependents,City,Zip Code,Latitude,Longitude,Number of Referrals,...,Payment Method,Monthly Charge,Total Charges,Total Refunds,Total Extra Data Charges,Total Long Distance Charges,Total Revenue,Customer Status,Churn Category,Churn Reason
0,0002-ORFBO,Female,37,Yes,0,Frazier Park,93225,34.827662,-118.999073,2,...,Credit Card,65.60,593.30,0.00,0,381.51,974.81,Stayed,NaN,NaN
1,0003-MKNFE,Male,46,No,0,Glendale,91206,34.162515,-118.203869,0,...,Credit Card,-4.00,542.40,38.33,10,96.21,610.28,Stayed,NaN,NaN
2,0004-TLHLJ,Male,50,No,0,Costa Mesa,92627,33.645672,-117.922613,0,...,Bank Withdrawal,73.90,280.85,0.00,0,134.60,415.45,Churned,Competitor,Competitor had better devices
3,0011-IGKFF,Male,78,Yes,0,Martinez,94553,38.014457,-122.115432,1,...,Bank Withdrawal,98.00,1237.85,0.00,0,361.66,1599.51,Churned,Dissatisfaction,Product dissatisfaction
4,0013-EXCHZ,Female,75,Yes,0,Camarillo,93010,34.227846,-119.079903,3,...,Credit Card,83.90,267.40,0.00,0,22.14,289.54,Churned,Dissatisfaction,Network reliability
5,0013-MHZWF,Female,23,No,3,Midpines,95345,37.581496,-119.972762,0,...,Credit Card,69.40,571.45,0.00,0,150.93,722.38,Stayed,NaN,NaN
6,0013-SMEOE,Female,67,Yes,0,Lompoc,93437,34.757477,-120.550507,1,...,Bank Withdrawal,109.70,7904.25,0.00,0,707.16,8611.41,Stayed,NaN,NaN
7,0014-BMAQU,Male,52,Yes,0,Napa,94558,38.489789,-122.270110,8,...,Credit Card,84.65,5377.80,0.00,20,816.48,6214.28,Stayed,NaN,NaN
8,0015-UOCOJ,Female,68,No,0,Simi Valley,93063,34.296813,-118.685703,0,...,Bank Withdrawal,48.20,340.35,0.00,0,73.71,414.06,Stayed,NaN,NaN
9,0016-QLJIS,Female,43,Yes,1,Sheridan,95681,38.984756,-121.345074,3,...,Credit Card,90.45,5957.90,0.00,0,1849.90,7807.80,Stayed,NaN,NaN

In [8]:
df.head(-100)

,Customer ID,Gender,Age,Married,Number of Dependents,City,Zip Code,Latitude,Longitude,Number of Referrals,...,Payment Method,Monthly Charge,Total Charges,Total Refunds,Total Extra Data Charges,Total Long Distance Charges,Total Revenue,Customer Status,Churn Category,Churn Reason
0,0002-ORFBO,Female,37,Yes,0,Frazier Park,93225,34.827662,-118.999073,2,...,Credit Card,65.60,593.30,0.00,0,381.51,974.81,Stayed,NaN,NaN
1,0003-MKNFE,Male,46,No,0,Glendale,91206,34.162515,-118.203869,0,...,Credit Card,-4.00,542.40,38.33,10,96.21,610.28,Stayed,NaN,NaN
2,0004-TLHLJ,Male,50,No,0,Costa Mesa,92627,33.645672,-117.922613,0,...,Bank Withdrawal,73.90,280.85,0.00,0,134.60,415.45,Churned,Competitor,Competitor had better devices
3,0011-IGKFF,Male,78,Yes,0,Martinez,94553,38.014457,-122.115432,1,...,Bank Withdrawal,98.00,1237.85,0.00,0,361.66,1599.51,Churned,Dissatisfaction,Product dissatisfaction
4,0013-EXCHZ,Female,75,Yes,0,Camarillo,93010,34.227846,-119.079903,3,...,Credit Card,83.90,267.40,0.00,0,22.14,289.54,Churned,Dissatisfaction,Network reliability
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6938,9840-EFJQB,Female,43,No,0,Sylmar,91342,34.321621,-118.399841,0,...,Bank Withdrawal,74.35,74.35,0.00,0,24.41,98.76,Joined,NaN,NaN
6939,9842-EFSYY,Female,31,No,3,Markleeville,96120,38.735789,-119.857980,0,...,Credit Card,57.20,223.75,0.00,0,0.00,223.75,Stayed,NaN,NaN
6940,9844-FELAJ,Female,65,Yes,2,Sacramento,95833,38.619049,-121.517552,2,...,Bank Withdrawal,107.90,7475.85,0.00,20,658.00,8153.85,Stayed,NaN,NaN
6941,9845-PEEKO,Female,71,No,0,Brookdale,95007,37.106902,-122.100006,0,...,Credit Card,79.20,4590.35,0.00,0,361.67,4952.02,Stayed,NaN,NaN
6942,9845-QOMAD,Male,38,Yes,2,Long Beach,90814,33.771612,-118.143866,6,...,Credit Card,19.75,309.35,6.49,0,377.86,680.72,Stayed,NaN,NaN

In [9]:
df.tail()

,Customer ID,Gender,Age,Married,Number of Dependents,City,Zip Code,Latitude,Longitude,Number of Referrals,...,Payment Method,Monthly Charge,Total Charges,Total Refunds,Total Extra Data Charges,Total Long Distance Charges,Total Revenue,Customer Status,Churn Category,Churn Reason
7038,9987-LUTYD,Female,20,No,0,La Mesa,91941,32.759327,-116.997260,0,...,Credit Card,55.15,742.90,0.0,0,606.84,1349.74,Stayed,NaN,NaN
7039,9992-RRAMN,Male,40,Yes,0,Riverbank,95367,37.734971,-120.954271,1,...,Bank Withdrawal,85.10,1873.70,0.0,0,356.40,2230.10,Churned,Dissatisfaction,Product dissatisfaction
7040,9992-UJOEL,Male,22,No,0,Elk,95432,39.108252,-123.645121,0,...,Credit Card,50.30,92.75,0.0,0,37.24,129.99,Joined,NaN,NaN
7041,9993-LHIEB,Male,21,Yes,0,Solana Beach,92075,33.001813,-117.263628,5,...,Credit Card,67.85,4627.65,0.0,0,142.04,4769.69,Stayed,NaN,NaN
7042,9995-HOTOH,Male,36,Yes,0,Sierra City,96125,39.600599,-120.636358,1,...,Bank Withdrawal,59.00,3707.60,0.0,0,0.00,3707.60,Stayed,NaN,NaN

In [10]:
df.tail(10)

,Customer ID,Gender,Age,Married,Number of Dependents,City,Zip Code,Latitude,Longitude,Number of Referrals,...,Payment Method,Monthly Charge,Total Charges,Total Refunds,Total Extra Data Charges,Total Long Distance Charges,Total Revenue,Customer Status,Churn Category,Churn Reason
7033,9975-SKRNR,Male,24,No,0,Sierraville,96126,39.559709,-120.345639,0,...,Credit Card,18.90,18.90,0.0,0,49.51,68.41,Joined,NaN,NaN
7034,9978-HYCIN,Male,72,Yes,1,Bakersfield,93301,35.383937,-119.020428,1,...,Bank Withdrawal,84.95,4018.05,0.0,80,1987.63,6085.68,Stayed,NaN,NaN
7035,9979-RGMZT,Female,20,No,0,Los Angeles,90022,34.023810,-118.156582,0,...,Credit Card,94.05,633.45,0.0,0,255.43,888.88,Stayed,NaN,NaN
7036,9985-MWVIX,Female,53,No,0,Hume,93628,36.807595,-118.901544,0,...,Credit Card,70.15,70.15,0.0,0,42.09,112.24,Churned,Competitor,Competitor had better devices
7037,9986-BONCE,Female,36,No,0,Fallbrook,92028,33.362575,-117.299644,0,...,Bank Withdrawal,20.95,85.50,0.0,0,8.04,93.54,Churned,Competitor,Competitor made better offer
7038,9987-LUTYD,Female,20,No,0,La Mesa,91941,32.759327,-116.997260,0,...,Credit Card,55.15,742.90,0.0,0,606.84,1349.74,Stayed,NaN,NaN
7039,9992-RRAMN,Male,40,Yes,0,Riverbank,95367,37.734971,-120.954271,1,...,Bank Withdrawal,85.10,1873.70,0.0,0,356.40,2230.10,Churned,Dissatisfaction,Product dissatisfaction
7040,9992-UJOEL,Male,22,No,0,Elk,95432,39.108252,-123.645121,0,...,Credit Card,50.30,92.75,0.0,0,37.24,129.99,Joined,NaN,NaN
7041,9993-LHIEB,Male,21,Yes,0,Solana Beach,92075,33.001813,-117.263628,5,...,Credit Card,67.85,4627.65,0.0,0,142.04,4769.69,Stayed,NaN,NaN
7042,9995-HOTOH,Male,36,Yes,0,Sierra City,96125,39.600599,-120.636358,1,...,Bank Withdrawal,59.00,3707.60,0.0,0,0.00,3707.60,Stayed,NaN,NaN

In [11]:
df.tail(-100)

,Customer ID,Gender,Age,Married,Number of Dependents,City,Zip Code,Latitude,Longitude,Number of Referrals,...,Payment Method,Monthly Charge,Total Charges,Total Refunds,Total Extra Data Charges,Total Long Distance Charges,Total Revenue,Customer Status,Churn Category,Churn Reason
100,0178-CIIKR,Female,60,No,0,Crows Landing,95313,37.435664,-121.049056,0,...,Credit Card,19.95,58.00,0.0,0,8.07,66.07,Joined,NaN,NaN
101,0178-SZBHO,Male,54,Yes,1,Tuolumne,95379,37.939768,-120.188002,7,...,Bank Withdrawal,87.20,4017.45,0.0,0,51.23,4068.68,Stayed,NaN,NaN
102,0181-RITDD,Male,42,Yes,3,San Diego,92120,32.807867,-117.060993,2,...,Credit Card,108.15,6825.65,0.0,0,109.12,6934.77,Stayed,NaN,NaN
103,0186-CAERR,Male,22,No,0,Auburn,95603,38.912881,-121.082766,0,...,Bank Withdrawal,116.30,8309.55,0.0,0,204.48,8514.03,Stayed,NaN,NaN
104,0187-QSXOE,Male,71,Yes,0,Fresno,93725,36.623632,-119.741322,8,...,Bank Withdrawal,89.00,605.45,0.0,0,293.79,899.24,Stayed,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,9987-LUTYD,Female,20,No,0,La Mesa,91941,32.759327,-116.997260,0,...,Credit Card,55.15,742.90,0.0,0,606.84,1349.74,Stayed,NaN,NaN
7039,9992-RRAMN,Male,40,Yes,0,Riverbank,95367,37.734971,-120.954271,1,...,Bank Withdrawal,85.10,1873.70,0.0,0,356.40,2230.10,Churned,Dissatisfaction,Product dissatisfaction
7040,9992-UJOEL,Male,22,No,0,Elk,95432,39.108252,-123.645121,0,...,Credit Card,50.30,92.75,0.0,0,37.24,129.99,Joined,NaN,NaN
7041,9993-LHIEB,Male,21,Yes,0,Solana Beach,92075,33.001813,-117.263628,5,...,Credit Card,67.85,4627.65,0.0,0,142.04,4769.69,Stayed,NaN,NaN
7042,9995-HOTOH,Male,36,Yes,0,Sierra City,96125,39.600599,-120.636358,1,...,Bank Withdrawal,59.00,3707.60,0.0,0,0.00,3707.60,Stayed,NaN,NaN

In [12]:
df.describe()

,Age,Number of Dependents,Zip Code,Latitude,Longitude,Number of Referrals,Tenure in Months,Avg Monthly Long Distance Charges,Avg Monthly GB Download,Monthly Charge,Total Charges,Total Refunds,Total Extra Data Charges,Total Long Distance Charges,Total Revenue
count,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,6361.000000,5517.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000
mean,46.509726,0.468692,93486.070567,36.197455,-119.756684,1.951867,32.386767,25.420517,26.189958,63.596131,2280.381264,1.962182,6.860713,749.099262,3034.379056
std,16.750352,0.962802,1856.767505,2.468929,2.154425,3.001199,24.542061,14.200374,19.586585,31.204743,2266.220462,7.902614,25.104978,846.660055,2865.204542
min,19.000000,0.000000,90001.000000,32.555828,-124.301372,0.000000,1.000000,1.010000,2.000000,-10.000000,18.800000,0.000000,0.000000,0.000000,21.360000
25%,32.000000,0.000000,92101.000000,33.990646,-121.788090,0.000000,9.000000,13.050000,13.000000,30.400000,400.150000,0.000000,0.000000,70.545000,605.610000
50%,46.000000,0.000000,93518.000000,36.205465,-119.595293,0.000000,29.000000,25.690000,21.000000,70.050000,1394.550000,0.000000,0.000000,401.440000,2108.640000
75%,60.000000,0.000000,95329.000000,38.161321,-117.969795,3.000000,55.000000,37.680000,30.000000,89.750000,3786.600000,0.000000,0.000000,1191.100000,4801.145000
max,80.000000,9.000000,96150.000000,41.962127,-114.192901,11.000000,72.000000,49.990000,85.000000,118.750000,8684.800000,49.790000,150.000000,3564.720000,11979.340000

In [13]:
df.describe(include=[object])

,Customer ID,Gender,Married,City,Offer,Phone Service,Multiple Lines,Internet Service,Internet Type,Online Security,...,Streaming TV,Streaming Movies,Streaming Music,Unlimited Data,Contract,Paperless Billing,Payment Method,Customer Status,Churn Category,Churn Reason
count,7043,7043,7043,7043,3166,7043,6361,7043,5517,5517,...,5517,5517,5517,5517,7043,7043,7043,7043,1869,1869
unique,7043,2,2,1106,5,2,2,2,3,2,...,2,2,2,2,3,2,3,3,5,20
top,0002-ORFBO,Male,No,Los Angeles,Offer B,Yes,No,Yes,Fiber Optic,No,...,No,No,No,Yes,Month-to-Month,Yes,Bank Withdrawal,Stayed,Competitor,Competitor had better devices
freq,1,3555,3641,293,824,6361,3390,5517,3035,3498,...,2810,2785,3029,4745,3610,4171,3909,4720,841,313

In [14]:
df.describe(exclude=[object])

,Age,Number of Dependents,Zip Code,Latitude,Longitude,Number of Referrals,Tenure in Months,Avg Monthly Long Distance Charges,Avg Monthly GB Download,Monthly Charge,Total Charges,Total Refunds,Total Extra Data Charges,Total Long Distance Charges,Total Revenue
count,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,6361.000000,5517.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000
mean,46.509726,0.468692,93486.070567,36.197455,-119.756684,1.951867,32.386767,25.420517,26.189958,63.596131,2280.381264,1.962182,6.860713,749.099262,3034.379056
std,16.750352,0.962802,1856.767505,2.468929,2.154425,3.001199,24.542061,14.200374,19.586585,31.204743,2266.220462,7.902614,25.104978,846.660055,2865.204542
min,19.000000,0.000000,90001.000000,32.555828,-124.301372,0.000000,1.000000,1.010000,2.000000,-10.000000,18.800000,0.000000,0.000000,0.000000,21.360000
25%,32.000000,0.000000,92101.000000,33.990646,-121.788090,0.000000,9.000000,13.050000,13.000000,30.400000,400.150000,0.000000,0.000000,70.545000,605.610000
50%,46.000000,0.000000,93518.000000,36.205465,-119.595293,0.000000,29.000000,25.690000,21.000000,70.050000,1394.550000,0.000000,0.000000,401.440000,2108.640000
75%,60.000000,0.000000,95329.000000,38.161321,-117.969795,3.000000,55.000000,37.680000,30.000000,89.750000,3786.600000,0.000000,0.000000,1191.100000,4801.145000
max,80.000000,9.000000,96150.000000,41.962127,-114.192901,11.000000,72.000000,49.990000,85.000000,118.750000,8684.800000,49.790000,150.000000,3564.720000,11979.340000

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 38 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Customer ID                        7043 non-null   object
 1   Gender                             7043 non-null   object
 2   Age                                7043 non-null   int64
 3   Married                            7043 non-null   object
 4   Number of Dependents               7043 non-null   int64
 5   City                               7043 non-null   object
 6   Zip Code                           7043 non-null   int64
 7   Latitude                           7043 non-null   float64
 8   Longitude                          7043 non-null   float64
 9   Number of Referrals                7043 non-null   int64
 10  Tenure in Months                   7043 non-null   int64
 11  Offer                              3166 non-null   object
 12  Phone Service                      7043 non-null   object
 13  Avg Monthly Long Distance Charges  6361 non-null   float64
 14  Multiple Lines                     6361 non-null   object
 15  Internet Service                   7043 non-null   object
 16  Internet Type                      5517 non-null   object
 17  Avg Monthly GB Download            5517 non-null   float64
 18  Online Security                    5517 non-null   object
 19  Online Backup                      5517 non-null   object
 20  Device Protection Plan             5517 non-null   object
 21  Premium Tech Support               5517 non-null   object
 22  Streaming TV                       5517 non-null   object
 23  Streaming Movies                   5517 non-null   object
 24  Streaming Music                    5517 non-null   object
 25  Unlimited Data                     5517 non-null   object
 26  Contract                           7043 non-null   object
 27  Paperless Billing                  7043 non-null   object
 28  Payment Method                     7043 non-null   object
 29  Monthly Charge                     7043 non-null   float64
 30  Total Charges                      7043 non-null   float64
 31  Total Refunds                      7043 non-null   float64
 32  Total Extra Data Charges           7043 non-null   int64
 33  Total Long Distance Charges        7043 non-null   float64
 34  Total Revenue                      7043 non-null   float64
 35  Customer Status                    7043 non-null   object
 36  Churn Category                     1869 non-null   object
 37  Churn Reason                       1869 non-null   object
dtypes: float64(9), int64(6), object(23)
memory usage: 2.0+ MB

In [16]:
type(df["Gender"])

pandas.core.series.Series

In [17]:
df

,Customer ID,Gender,Age,Married,Number of Dependents,City,Zip Code,Latitude,Longitude,Number of Referrals,...,Payment Method,Monthly Charge,Total Charges,Total Refunds,Total Extra Data Charges,Total Long Distance Charges,Total Revenue,Customer Status,Churn Category,Churn Reason
0,0002-ORFBO,Female,37,Yes,0,Frazier Park,93225,34.827662,-118.999073,2,...,Credit Card,65.60,593.30,0.00,0,381.51,974.81,Stayed,NaN,NaN
1,0003-MKNFE,Male,46,No,0,Glendale,91206,34.162515,-118.203869,0,...,Credit Card,-4.00,542.40,38.33,10,96.21,610.28,Stayed,NaN,NaN
2,0004-TLHLJ,Male,50,No,0,Costa Mesa,92627,33.645672,-117.922613,0,...,Bank Withdrawal,73.90,280.85,0.00,0,134.60,415.45,Churned,Competitor,Competitor had better devices
3,0011-IGKFF,Male,78,Yes,0,Martinez,94553,38.014457,-122.115432,1,...,Bank Withdrawal,98.00,1237.85,0.00,0,361.66,1599.51,Churned,Dissatisfaction,Product dissatisfaction
4,0013-EXCHZ,Female,75,Yes,0,Camarillo,93010,34.227846,-119.079903,3,...,Credit Card,83.90,267.40,0.00,0,22.14,289.54,Churned,Dissatisfaction,Network reliability
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,9987-LUTYD,Female,20,No,0,La Mesa,91941,32.759327,-116.997260,0,...,Credit Card,55.15,742.90,0.00,0,606.84,1349.74,Stayed,NaN,NaN
7039,9992-RRAMN,Male,40,Yes,0,Riverbank,95367,37.734971,-120.954271,1,...,Bank Withdrawal,85.10,1873.70,0.00,0,356.40,2230.10,Churned,Dissatisfaction,Product dissatisfaction
7040,9992-UJOEL,Male,22,No,0,Elk,95432,39.108252,-123.645121,0,...,Credit Card,50.30,92.75,0.00,0,37.24,129.99,Joined,NaN,NaN
7041,9993-LHIEB,Male,21,Yes,0,Solana Beach,92075,33.001813,-117.263628,5,...,Credit Card,67.85,4627.65,0.00,0,142.04,4769.69,Stayed,NaN,NaN
7042,9995-HOTOH,Male,36,Yes,0,Sierra City,96125,39.600599,-120.636358,1,...,Bank Withdrawal,59.00,3707.60,0.00,0,0.00,3707.60,Stayed,NaN,NaN

In [18]:
df['Multiple Lines']=df['Multiple Lines'].replace({'Yes':1,'No':0})

/tmp/ipykernel_13030/3011508853.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Multiple Lines']=df['Multiple Lines'].replace({'Yes':1,'No':0})

In [19]:
df['Gender'] = df['Gender'].replace({'Female':1, 'Male':0})

/tmp/ipykernel_13030/4001803221.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Gender'] = df['Gender'].replace({'Female':1, 'Male':0})

In [20]:
df['Premium Tech Support'] = df['Premium Tech Support'].replace({'Yes':1, 'No':0})

/tmp/ipykernel_13030/2435158813.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Premium Tech Support'] = df['Premium Tech Support'].replace({'Yes':1, 'No':0})

In [21]:
df['Streaming TV'] = df['Streaming TV'].replace({'Yes':1, 'No':0})

/tmp/ipykernel_13030/2382689176.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Streaming TV'] = df['Streaming TV'].replace({'Yes':1, 'No':0})

In [22]:
df['Streaming Movies'] = df['Streaming Movies'].replace({'Yes':1, 'No':0})

/tmp/ipykernel_13030/1596363127.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Streaming Movies'] = df['Streaming Movies'].replace({'Yes':1, 'No':0})

In [23]:
df['Streaming Music'] = df['Streaming Music'].replace({'Yes':1, 'No':0})

/tmp/ipykernel_13030/3163307251.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Streaming Music'] = df['Streaming Music'].replace({'Yes':1, 'No':0})

In [24]:
df['Unlimited Data'] = df['Unlimited Data'].replace({'Yes':1, 'No':0})

/tmp/ipykernel_13030/2768738965.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Unlimited Data'] = df['Unlimited Data'].replace({'Yes':1, 'No':0})

In [25]:
df['Paperless Billing'] = df['Paperless Billing'].replace({'Yes':1, 'No':0})

/tmp/ipykernel_13030/1909443592.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Paperless Billing'] = df['Paperless Billing'].replace({'Yes':1, 'No':0})

In [26]:
df['Device Protection Plan'] = df['Device Protection Plan'].replace({'Yes':1, 'No':0})

/tmp/ipykernel_13030/4132773544.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Device Protection Plan'] = df['Device Protection Plan'].replace({'Yes':1, 'No':0})

In [27]:
df['Internet Service'] = df['Internet Service'].replace({'Yes':1, 'No':0})

/tmp/ipykernel_13030/1470666216.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Internet Service'] = df['Internet Service'].replace({'Yes':1, 'No':0})

In [28]:
df['Online Backup'] = df['Online Backup'].replace({'Yes':1, 'No':0})

/tmp/ipykernel_13030/8910303.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Online Backup'] = df['Online Backup'].replace({'Yes':1, 'No':0})

In [29]:
df['Online Security'] = df['Online Security'].replace({'Yes':1, 'No':0})

/tmp/ipykernel_13030/109156700.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Online Security'] = df['Online Security'].replace({'Yes':1, 'No':0})

In [30]:
df['Phone Service'] = df['Phone Service'].replace({'Yes':1, 'No':0})

/tmp/ipykernel_13030/2819535287.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Phone Service'] = df['Phone Service'].replace({'Yes':1, 'No':0})

In [31]:
df['Married'] = df['Married'].replace({'Yes':1, 'No':0})

/tmp/ipykernel_13030/279952452.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Married'] = df['Married'].replace({'Yes':1, 'No':0})

In [32]:
df['Total Revenue'].max()

11979.34

In [33]:
count=df["Total Revenue"].between(11000,120000).sum()
print(count)

27

In [34]:
count=df['Avg Monthly Long Distance Charges'].between(40,45).sum()
print(count)

647

In [35]:
count=df['Total Charges'].between(0,0.2).sum()
print(count)

0

In [36]:
count=df['Avg Monthly GB Download'].between(0,10).sum()
print(count)

1087

In [37]:
df['Gender'][200]

0

In [38]:
df.iloc[[980],[1]]

     Gender
980       0

In [39]:
df.iloc[1,8]

-118.203869

In [40]:
df.loc[980]

Customer ID                               1422-DGUBX
Gender                                             0
Age                                               64
Married                                            1
Number of Dependents                               0
City                                      Sacramento
Zip Code                                       95832
Latitude                                   38.445939
Longitude                                -121.496855
Number of Referrals                                4
Tenure in Months                                  32
Offer                                            NaN
Phone Service                                      1
Avg Monthly Long Distance Charges              43.11
Multiple Lines                                   1.0
Internet Service                                   1
Internet Type                            Fiber Optic
Avg Monthly GB Download                         18.0
Online Security                                  0.0
Online Backup                                    0.0
Device Protection Plan                           0.0
Premium Tech Support                             1.0
Streaming TV                                     0.0
Streaming Movies                                 0.0
Streaming Music                                  0.0
Unlimited Data                                   1.0
Contract                                    One Year
Paperless Billing                                  1
Payment Method                       Bank Withdrawal
Monthly Charge                                 79.25
Total Charges                                2619.15
Total Refunds                                  16.96
Total Extra Data Charges                           0
Total Long Distance Charges                  1379.52
Total Revenue                                3981.71
Customer Status                               Stayed
Churn Category                                   NaN
Churn Reason                                     NaN
Name: 980, dtype: object

In [41]:
df.loc[[980,456]]

,Customer ID,Gender,Age,Married,Number of Dependents,City,Zip Code,Latitude,Longitude,Number of Referrals,...,Payment Method,Monthly Charge,Total Charges,Total Refunds,Total Extra Data Charges,Total Long Distance Charges,Total Revenue,Customer Status,Churn Category,Churn Reason
980,1422-DGUBX,0,64,1,0,Sacramento,95832,38.445939,-121.496855,4,...,Bank Withdrawal,79.25,2619.15,16.96,0,1379.52,3981.71,Stayed,NaN,NaN
456,0670-ANMUU,0,47,0,0,Chino Hills,91709,33.942895,-117.725644,0,...,Credit Card,97.65,6687.85,0.00,0,1176.47,7864.32,Stayed,NaN,NaN

In [42]:
df.loc[[980,456],['Gender','Married']]

     Gender  Married
980       0        1
456       0        0

In [43]:
df.loc[45,'Longitude']

-119.372842

In [44]:
df[0:3]

,Customer ID,Gender,Age,Married,Number of Dependents,City,Zip Code,Latitude,Longitude,Number of Referrals,...,Payment Method,Monthly Charge,Total Charges,Total Refunds,Total Extra Data Charges,Total Long Distance Charges,Total Revenue,Customer Status,Churn Category,Churn Reason
0,0002-ORFBO,1,37,1,0,Frazier Park,93225,34.827662,-118.999073,2,...,Credit Card,65.6,593.30,0.00,0,381.51,974.81,Stayed,NaN,NaN
1,0003-MKNFE,0,46,0,0,Glendale,91206,34.162515,-118.203869,0,...,Credit Card,-4.0,542.40,38.33,10,96.21,610.28,Stayed,NaN,NaN
2,0004-TLHLJ,0,50,0,0,Costa Mesa,92627,33.645672,-117.922613,0,...,Bank Withdrawal,73.9,280.85,0.00,0,134.60,415.45,Churned,Competitor,Competitor had better devices

In [45]:
df.at[700,'Married']

1

In [46]:
df_copy=df.copy()
print(df_copy)

     Customer ID  Gender  Age  Married  Number of Dependents          City  \
0     0002-ORFBO       1   37        1                     0  Frazier Park
1     0003-MKNFE       0   46        0                     0      Glendale
2     0004-TLHLJ       0   50        0                     0    Costa Mesa
3     0011-IGKFF       0   78        1                     0      Martinez
4     0013-EXCHZ       1   75        1                     0     Camarillo
...          ...     ...  ...      ...                   ...           ...
7038  9987-LUTYD       1   20        0                     0       La Mesa
7039  9992-RRAMN       0   40        1                     0     Riverbank
7040  9992-UJOEL       0   22        0                     0           Elk
7041  9993-LHIEB       0   21        1                     0  Solana Beach
7042  9995-HOTOH       0   36        1                     0   Sierra City

      Zip Code   Latitude   Longitude  Number of Referrals  ...  \
0        93225  34.827662 -118.999073                    2  ...
1        91206  34.162515 -118.203869                    0  ...
2        92627  33.645672 -117.922613                    0  ...
3        94553  38.014457 -122.115432                    1  ...
4        93010  34.227846 -119.079903                    3  ...
...        ...        ...         ...                  ...  ...
7038     91941  32.759327 -116.997260                    0  ...
7039     95367  37.734971 -120.954271                    1  ...
7040     95432  39.108252 -123.645121                    0  ...
7041     92075  33.001813 -117.263628                    5  ...
7042     96125  39.600599 -120.636358                    1  ...

       Payment Method Monthly Charge  Total Charges  Total Refunds  \
0         Credit Card          65.60         593.30           0.00
1         Credit Card          -4.00         542.40          38.33
2     Bank Withdrawal          73.90         280.85           0.00
3     Bank Withdrawal          98.00        1237.85           0.00
4         Credit Card          83.90         267.40           0.00
...               ...            ...            ...            ...
7038      Credit Card          55.15         742.90           0.00
7039  Bank Withdrawal          85.10        1873.70           0.00
7040      Credit Card          50.30          92.75           0.00
7041      Credit Card          67.85        4627.65           0.00
7042  Bank Withdrawal          59.00        3707.60           0.00

      Total Extra Data Charges  Total Long Distance Charges Total Revenue  \
0                            0                       381.51        974.81
1                           10                        96.21        610.28
2                            0                       134.60        415.45
3                            0                       361.66       1599.51
4                            0                        22.14        289.54
...                        ...                          ...           ...
7038                         0                       606.84       1349.74
7039                         0                       356.40       2230.10
7040                         0                        37.24        129.99
7041                         0                       142.04       4769.69
7042                         0                         0.00       3707.60

      Customer Status   Churn Category                   Churn Reason
0              Stayed              NaN                            NaN
1              Stayed              NaN                            NaN
2             Churned       Competitor  Competitor had better devices
3             Churned  Dissatisfaction        Product dissatisfaction
4             Churned  Dissatisfaction            Network reliability
...               ...              ...                            ...
7038           Stayed              NaN                            NaN
7039          Churned  Dissatisfaction        Product dissatisfaction
7040           Joined              NaN                            NaN
7041           Stayed              NaN                            NaN
7042           Stayed              NaN                            NaN

[7043 rows x 38 columns]

In [47]:
print(df_copy.at[500,"Gender"])

0

In [48]:
df_copy.at[500,'Gender']='1'
df_copy.iloc[[500],[1]]

/tmp/ipykernel_13030/2115361419.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df_copy.at[500,'Gender']='1'

    Gender
500      1

In [49]:
df_copy.at[500,'Gender']

'1'

In [50]:
print(df.at[500,"Gender"])

0

In [51]:
df[0:3]

,Customer ID,Gender,Age,Married,Number of Dependents,City,Zip Code,Latitude,Longitude,Number of Referrals,...,Payment Method,Monthly Charge,Total Charges,Total Refunds,Total Extra Data Charges,Total Long Distance Charges,Total Revenue,Customer Status,Churn Category,Churn Reason
0,0002-ORFBO,1,37,1,0,Frazier Park,93225,34.827662,-118.999073,2,...,Credit Card,65.6,593.30,0.00,0,381.51,974.81,Stayed,NaN,NaN
1,0003-MKNFE,0,46,0,0,Glendale,91206,34.162515,-118.203869,0,...,Credit Card,-4.0,542.40,38.33,10,96.21,610.28,Stayed,NaN,NaN
2,0004-TLHLJ,0,50,0,0,Costa Mesa,92627,33.645672,-117.922613,0,...,Bank Withdrawal,73.9,280.85,0.00,0,134.60,415.45,Churned,Competitor,Competitor had better devices

In [52]:
df.loc[7:9]

,Customer ID,Gender,Age,Married,Number of Dependents,City,Zip Code,Latitude,Longitude,Number of Referrals,...,Payment Method,Monthly Charge,Total Charges,Total Refunds,Total Extra Data Charges,Total Long Distance Charges,Total Revenue,Customer Status,Churn Category,Churn Reason
7,0014-BMAQU,0,52,1,0,Napa,94558,38.489789,-122.270110,8,...,Credit Card,84.65,5377.80,0.0,20,816.48,6214.28,Stayed,NaN,NaN
8,0015-UOCOJ,1,68,0,0,Simi Valley,93063,34.296813,-118.685703,0,...,Bank Withdrawal,48.20,340.35,0.0,0,73.71,414.06,Stayed,NaN,NaN
9,0016-QLJIS,1,43,1,1,Sheridan,95681,38.984756,-121.345074,3,...,Credit Card,90.45,5957.90,0.0,0,1849.90,7807.80,Stayed,NaN,NaN

In [53]:
df.loc[23:45,'Gender']

23    1
24    1
25    1
26    1
27    0
28    0
29    1
30    0
31    1
32    0
33    1
34    0
35    1
36    1
37    1
38    1
39    0
40    0
41    1
42    0
43    0
44    0
45    0
Name: Gender, dtype: int64

In [54]:
df.loc[10:20,"Gender":"Payment Method"]

,Gender,Age,Married,Number of Dependents,City,Zip Code,Latitude,Longitude,Number of Referrals,Tenure in Months,...,Online Backup,Device Protection Plan,Premium Tech Support,Streaming TV,Streaming Movies,Streaming Music,Unlimited Data,Contract,Paperless Billing,Payment Method
10,0,47,0,0,Rancho Santa Fe,92091,32.993560,-117.207121,0,54,...,0.0,0.0,1.0,1.0,0.0,0.0,1.0,Two Year,0,Credit Card
11,1,25,1,2,Sunnyvale,94086,37.378541,-122.020456,2,72,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,Two Year,1,Credit Card
12,1,58,1,0,Antelope,95843,38.715498,-121.363411,0,5,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,Month-to-Month,1,Bank Withdrawal
13,1,32,0,0,La Mesa,91942,32.782501,-117.016110,0,72,...,1.0,1.0,0.0,1.0,0.0,0.0,1.0,Two Year,1,Bank Withdrawal
14,1,39,0,0,Los Olivos,93441,34.704340,-120.026090,0,56,...,1.0,1.0,1.0,0.0,0.0,0.0,1.0,Two Year,0,Bank Withdrawal
15,1,58,1,2,Woodlake,93286,36.464635,-119.094348,9,71,...,1.0,1.0,0.0,0.0,1.0,1.0,1.0,Two Year,1,Credit Card
16,1,52,1,1,Point Reyes Station,94956,38.060264,-122.830646,0,34,...,0.0,1.0,1.0,1.0,1.0,1.0,1.0,One Year,0,Credit Card
17,1,72,0,0,San Marcos,92078,33.119028,-117.166036,0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,One Year,1,Bank Withdrawal
18,0,79,0,0,Daly City,94015,37.680844,-122.481310,0,45,...,0.0,1.0,0.0,0.0,1.0,0.0,1.0,One Year,0,Credit Card
19,0,67,0,0,Morgan Hill,95037,37.161544,-121.649371,0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,Month-to-Month,1,Bank Withdrawal
20,1,79,1,0,Ahwahnee,93601,37.375816,-119.739935,0,50,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,One Year,0,Bank Withdrawal

In [55]:
df.iloc[1:2,0:3]

  Customer ID  Gender  Age
1  0003-MKNFE       0   46

In [56]:
df.iloc[1,0:3]

Customer ID    0003-MKNFE
Gender                  0
Age                    46
Name: 1, dtype: object

DATA CLEANING


HANDLING MISSING VALUES..

In [57]:
df.isna()

,Customer ID,Gender,Age,Married,Number of Dependents,City,Zip Code,Latitude,Longitude,Number of Referrals,...,Payment Method,Monthly Charge,Total Charges,Total Refunds,Total Extra Data Charges,Total Long Distance Charges,Total Revenue,Customer Status,Churn Category,Churn Reason
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,True
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,True
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,True
7039,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7040,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,True
7041,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,True
7042,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,True

In [58]:
df["Payment Method"].isna()

0       False
1       False
2       False
3       False
4       False
        ...
7038    False
7039    False
7040    False
7041    False
7042    False
Name: Payment Method, Length: 7043, dtype: bool

In [59]:
df.isna().sum()

Customer ID                             0
Gender                                  0
Age                                     0
Married                                 0
Number of Dependents                    0
City                                    0
Zip Code                                0
Latitude                                0
Longitude                               0
Number of Referrals                     0
Tenure in Months                        0
Offer                                3877
Phone Service                           0
Avg Monthly Long Distance Charges     682
Multiple Lines                        682
Internet Service                        0
Internet Type                        1526
Avg Monthly GB Download              1526
Online Security                      1526
Online Backup                        1526
Device Protection Plan               1526
Premium Tech Support                 1526
Streaming TV                         1526
Streaming Movies                     1526
Streaming Music                      1526
Unlimited Data                       1526
Contract                                0
Paperless Billing                       0
Payment Method                          0
Monthly Charge                          0
Total Charges                           0
Total Refunds                           0
Total Extra Data Charges                0
Total Long Distance Charges             0
Total Revenue                           0
Customer Status                         0
Churn Category                       5174
Churn Reason                         5174
dtype: int64

In [60]:
(df.isnull().sum() / len(df)) * 100

Customer ID                           0.000000
Gender                                0.000000
Age                                   0.000000
Married                               0.000000
Number of Dependents                  0.000000
City                                  0.000000
Zip Code                              0.000000
Latitude                              0.000000
Longitude                             0.000000
Number of Referrals                   0.000000
Tenure in Months                      0.000000
Offer                                55.047565
Phone Service                         0.000000
Avg Monthly Long Distance Charges     9.683374
Multiple Lines                        9.683374
Internet Service                      0.000000
Internet Type                        21.666903
Avg Monthly GB Download              21.666903
Online Security                      21.666903
Online Backup                        21.666903
Device Protection Plan               21.666903
Premium Tech Support                 21.666903
Streaming TV                         21.666903
Streaming Movies                     21.666903
Streaming Music                      21.666903
Unlimited Data                       21.666903
Contract                              0.000000
Paperless Billing                     0.000000
Payment Method                        0.000000
Monthly Charge                        0.000000
Total Charges                         0.000000
Total Refunds                         0.000000
Total Extra Data Charges              0.000000
Total Long Distance Charges           0.000000
Total Revenue                         0.000000
Customer Status                       0.000000
Churn Category                       73.463013
Churn Reason                         73.463013
dtype: float64

**Filling  Numeric Null values with Mean**

In [61]:
# For numerical columns
df.fillna(df.mean(numeric_only=True), inplace=True)

# For categorical columns
df.fillna(df.mode().iloc[0], inplace=True)

In [62]:
df.drop(['Customer ID', 'Zip Code','City','Offer'], axis=1, inplace=True, errors='ignore')

In [63]:
df['Customer Status'] = df['Customer Status'].map({
    'Stayed': 0,
    'Churned': 1,
    'Joined': 2
})

In [64]:
cat_cols = df.select_dtypes(include='object').columns
num_cols = df.select_dtypes(exclude='object').columns

In [65]:
df = pd.get_dummies(df, columns=cat_cols)

Drop Null Values

In [66]:
df.dropna()

,Gender,Age,Married,Number of Dependents,Latitude,Longitude,Number of Referrals,Tenure in Months,Phone Service,Avg Monthly Long Distance Charges,...,Churn Reason_Lack of self-service on Website,Churn Reason_Limited range of services,Churn Reason_Long distance charges,Churn Reason_Moved,Churn Reason_Network reliability,Churn Reason_Poor expertise of online support,Churn Reason_Poor expertise of phone support,Churn Reason_Price too high,Churn Reason_Product dissatisfaction,Churn Reason_Service dissatisfaction
0,1,37,1,0,34.827662,-118.999073,2,9,1,42.390000,...,False,False,False,False,False,False,False,False,False,False
1,0,46,0,0,34.162515,-118.203869,0,9,1,10.690000,...,False,False,False,False,False,False,False,False,False,False
2,0,50,0,0,33.645672,-117.922613,0,4,1,33.650000,...,False,False,False,False,False,False,False,False,False,False
3,0,78,1,0,38.014457,-122.115432,1,13,1,27.820000,...,False,False,False,False,False,False,False,False,True,False
4,1,75,1,0,34.227846,-119.079903,3,3,1,7.380000,...,False,False,False,False,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,1,20,0,0,32.759327,-116.997260,0,13,1,46.680000,...,False,False,False,False,False,False,False,False,False,False
7039,0,40,1,0,37.734971,-120.954271,1,22,1,16.200000,...,False,False,False,False,False,False,False,False,True,False
7040,0,22,0,0,39.108252,-123.645121,0,2,1,18.620000,...,False,False,False,False,False,False,False,False,False,False
7041,0,21,1,0,33.001813,-117.263628,5,67,1,2.120000,...,False,False,False,False,False,False,False,False,False,False
7042,0,36,1,0,39.600599,-120.636358,1,63,0,25.420517,...,False,False,False,False,False,False,False,False,False,False

In [67]:
df.dropna(how='all')

,Gender,Age,Married,Number of Dependents,Latitude,Longitude,Number of Referrals,Tenure in Months,Phone Service,Avg Monthly Long Distance Charges,...,Churn Reason_Lack of self-service on Website,Churn Reason_Limited range of services,Churn Reason_Long distance charges,Churn Reason_Moved,Churn Reason_Network reliability,Churn Reason_Poor expertise of online support,Churn Reason_Poor expertise of phone support,Churn Reason_Price too high,Churn Reason_Product dissatisfaction,Churn Reason_Service dissatisfaction
0,1,37,1,0,34.827662,-118.999073,2,9,1,42.390000,...,False,False,False,False,False,False,False,False,False,False
1,0,46,0,0,34.162515,-118.203869,0,9,1,10.690000,...,False,False,False,False,False,False,False,False,False,False
2,0,50,0,0,33.645672,-117.922613,0,4,1,33.650000,...,False,False,False,False,False,False,False,False,False,False
3,0,78,1,0,38.014457,-122.115432,1,13,1,27.820000,...,False,False,False,False,False,False,False,False,True,False
4,1,75,1,0,34.227846,-119.079903,3,3,1,7.380000,...,False,False,False,False,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,1,20,0,0,32.759327,-116.997260,0,13,1,46.680000,...,False,False,False,False,False,False,False,False,False,False
7039,0,40,1,0,37.734971,-120.954271,1,22,1,16.200000,...,False,False,False,False,False,False,False,False,True,False
7040,0,22,0,0,39.108252,-123.645121,0,2,1,18.620000,...,False,False,False,False,False,False,False,False,False,False
7041,0,21,1,0,33.001813,-117.263628,5,67,1,2.120000,...,False,False,False,False,False,False,False,False,False,False
7042,0,36,1,0,39.600599,-120.636358,1,63,0,25.420517,...,False,False,False,False,False,False,False,False,False,False

In [68]:
df.dropna(axis='columns',how='any')

,Gender,Age,Married,Number of Dependents,Latitude,Longitude,Number of Referrals,Tenure in Months,Phone Service,Avg Monthly Long Distance Charges,...,Churn Reason_Lack of self-service on Website,Churn Reason_Limited range of services,Churn Reason_Long distance charges,Churn Reason_Moved,Churn Reason_Network reliability,Churn Reason_Poor expertise of online support,Churn Reason_Poor expertise of phone support,Churn Reason_Price too high,Churn Reason_Product dissatisfaction,Churn Reason_Service dissatisfaction
0,1,37,1,0,34.827662,-118.999073,2,9,1,42.390000,...,False,False,False,False,False,False,False,False,False,False
1,0,46,0,0,34.162515,-118.203869,0,9,1,10.690000,...,False,False,False,False,False,False,False,False,False,False
2,0,50,0,0,33.645672,-117.922613,0,4,1,33.650000,...,False,False,False,False,False,False,False,False,False,False
3,0,78,1,0,38.014457,-122.115432,1,13,1,27.820000,...,False,False,False,False,False,False,False,False,True,False
4,1,75,1,0,34.227846,-119.079903,3,3,1,7.380000,...,False,False,False,False,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,1,20,0,0,32.759327,-116.997260,0,13,1,46.680000,...,False,False,False,False,False,False,False,False,False,False
7039,0,40,1,0,37.734971,-120.954271,1,22,1,16.200000,...,False,False,False,False,False,False,False,False,True,False
7040,0,22,0,0,39.108252,-123.645121,0,2,1,18.620000,...,False,False,False,False,False,False,False,False,False,False
7041,0,21,1,0,33.001813,-117.263628,5,67,1,2.120000,...,False,False,False,False,False,False,False,False,False,False
7042,0,36,1,0,39.600599,-120.636358,1,63,0,25.420517,...,False,False,False,False,False,False,False,False,False,False

HANDLING DUPLICATES

In [69]:
df[25:37].duplicated()

25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
dtype: bool

In [70]:
df[25:37].duplicated(keep='last')

25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
dtype: bool

In [71]:
df[0:10].duplicated(subset=['Gender'])

0    False
1    False
2     True
3     True
4     True
5     True
6     True
7     True
8     True
9     True
dtype: bool

Drop Duplicates

In [72]:
tel_df=df[25:78]
tel_df

,Gender,Age,Married,Number of Dependents,Latitude,Longitude,Number of Referrals,Tenure in Months,Phone Service,Avg Monthly Long Distance Charges,...,Churn Reason_Lack of self-service on Website,Churn Reason_Limited range of services,Churn Reason_Long distance charges,Churn Reason_Moved,Churn Reason_Network reliability,Churn Reason_Poor expertise of online support,Churn Reason_Poor expertise of phone support,Churn Reason_Price too high,Churn Reason_Product dissatisfaction,Churn Reason_Service dissatisfaction
25,1,37,1,1,33.309852,-116.823091,1,1,0,25.420517,...,False,False,False,False,False,False,False,False,False,False
26,1,37,1,3,36.622237,-119.521126,10,55,1,35.040000,...,False,False,False,False,False,False,False,False,False,False
27,0,42,1,3,37.612612,-121.108568,3,54,1,19.700000,...,False,False,False,False,False,False,False,False,False,False
28,0,64,0,0,38.368744,-122.522642,0,26,1,37.700000,...,False,False,False,False,False,False,False,False,False,False
29,1,47,1,3,40.737431,-124.108897,5,69,1,38.390000,...,False,False,False,False,False,False,False,False,False,False
30,0,23,1,3,37.515556,-122.502311,1,37,1,43.010000,...,False,False,False,False,False,False,False,False,False,False
31,1,48,1,0,34.001617,-118.222274,5,49,1,49.580000,...,False,False,False,False,False,False,False,False,False,False
32,0,28,1,0,34.044271,-118.185237,9,66,1,43.770000,...,False,False,False,False,False,False,False,False,False,False
33,1,28,0,0,32.690654,-115.431225,0,67,1,23.120000,...,False,False,False,False,False,False,False,False,False,False
34,0,33,1,1,40.677649,-122.294670,4,20,0,25.420517,...,False,False,False,False,False,False,False,False,False,False
35,1,31,0,3,37.084697,-121.606417,0,43,1,30.640000,...,False,False,False,False,False,False,False,False,False,False
36,1,37,1,0,38.044523,-121.348048,2,55,1,5.080000,...,False,False,False,False,False,False,False,False,False,False
37,1,60,1,0,33.964131,-118.272783,4,59,1,16.390000,...,False,False,False,False,False,False,False,False,False,False
38,1,48,1,3,33.978030,-118.217141,3,12,1,19.280000,...,False,False,False,False,False,False,False,False,False,False
39,0,60,1,3,35.013299,-116.834092,7,27,1,25.260000,...,False,False,False,False,False,False,False,False,False,False
40,0,69,0,0,32.961064,-117.134917,0,2,1,43.990000,...,False,False,False,False,False,False,False,False,False,False
41,1,20,0,0,37.516791,-121.899117,0,27,1,48.910000,...,False,False,False,False,False,False,False,False,False,False
42,0,31,1,3,38.439696,-122.668817,1,25,1,23.690000,...,False,False,False,False,False,False,False,False,False,False
43,0,46,1,0,37.327069,-121.916819,5,25,1,6.450000,...,False,False,False,False,False,False,False,False,False,False
44,0,57,0,1,34.296574,-118.244839,0,29,0,25.420517,...,False,False,False,False,False,False,False,False,False,False
45,0,19,1,0,36.391777,-119.372842,5,72,1,32.360000,...,False,False,False,False,False,False,False,False,False,False
46,1,64,0,0,38.123544,-121.159078,0,14,1,24.040000,...,False,False,False,False,False,False,False,False,False,False
47,1,38,0,0,37.654551,-119.822984,0,35,1,36.420000,...,False,False,False,False,False,False,False,False,False,False
48,0,54,0,0,38.629618,-122.593216,0,1,1,42.950000,...,False,False,False,False,False,False,False,False,False,False
49,0,50,0,0,37.956963,-120.863055,0,29,1,2.050000,...,False,False,False,False,False,False,False,False,False,False
50,0,25,0,0,41.813521,-121.492666,0,64,1,5.490000,...,False,False,False,False,False,False,False,False,False,False
51,1,35,1,3,38.425280,-119.475741,1,39,1,24.380000,...,False,False,False,False,False,False,False,False,False,False
52,1,72,0,0,34.581308,-118.931948,0,40,1,44.140000,...,False,False,False,False,False,False,False,False,False,False
53,0,51,0,0,33.832799,-116.250973,0,40,1,37.690000,...,False,False,False,False,False,False,False,False,False,False
54,1,78,0,1,34.207295,-118.400022,0,11,1,11.590000,...,False,False,False,False,False,False,False,False,True,False
55,1,30,1,0,38.099323,-122.945723,10,6,1,42.660000,...,False,False,False,False,False,False,False,False,False,False
56,0,58,0,0,38.526941,-122.709096,0,30,1,2.640000,...,False,False,False,False,False,False,False,False,False,False
57,0,26,0,0,37.387027,-121.897775,0,27,1,20.660000,...,False,False,False,False,False,False,False,False,False,False
58,0,66,1,0,33.782068,-118.262263,3,70,1,39.490000,...,False,False,False,False,False,False,False,False,False,False
59,1,20,1,0,37.670526,-120.877572,10,57,1,8.010000,...,False,False,False,False,False,False,False,False,False,False
60,0,61,1,0,32.697098,-117.116587,10,58,1,18.370000,...,False,False,False,False,False,False,False,False,False,False
61,0,24,0,0,33.753146,-118.367459,0,16,1,25.710000,...,False,False,False,False,False,False,False,False,False,False
62,1,55,1,0,38.419525,-122.521585,3,69,1,38.520000,...,False,False,False,False,False,False,False,False,False,False
63,0,32,0,0,38.419350,-120.469545,0,1,1,31.770000,...,False,False,False,False,False,False,False,False,False,False
64,0,59,0,0,34.003553,-118.308933,0,1,1,40.710000,...,False,False,False,False,False,False,False,False,False,False
65,0,71,1,1,34.097863,-116.594561,9,32,1,31.860000,...,False,False,False,False,False,False,False,False,False,False
66,0,49,1,2,33.324900,-114.758334,8,16,1,48.710000,...,False,False,False,False,False,False,False,False,False,False
67,0,61,1,0,34.395830,-117.734568,1,49,1,39.550000,...,False,False,False,False,False,False,False,False,False,False
68,1,40,1,0,35.591387,-121.032256,2,71,0,25.420517,...,False,False,False,False,False,False,False,False,False,False
69,1,39,0,0,40.923558,-122.059933,0,33,1,49.690000,...,False,False,False,False,False,False,False,False,False,False
70,1,21,1,0,41.572813,-124.035011,9,10,1,49.600000,...,False,False,False,False,False,False,False,False,False,False
71,0,24,1,0,36.841655,-119.797113,1,21,1,36.260000,...,False,False,False,False,False,False,False,False,False,False
72,0,52,1,1,38.542448,-122.419923,1,37,0,25.420517,...,False,False,False,False,False,False,False,False,False,False
73,1,71,0,0,37.249377,-120.249581,0,26,1,33.740000,...,False,False,False,False,False,False,False,False,False,False
74,0,45,0,0,40.142256,-123.852927,0,50,0,25.420517,...,False,False,False,False,False,False,False,False,False,False
75,1,29,0,0,32.857230,-117.209774,0,7,1,28.620000,...,False,False,False,False,False,False,False,False,False,False
76,1,62,1,0,34.049172,-118.115022,1,61,1,47.190000,...,False,False,False,False,False,False,False,False,False,False
77,0,42,0,0,37.818589,-120.256995,0,15,1,45.920000,...,False,False,False,False,False,False,False,False,False,False

In [73]:
tel_df.drop_duplicates()

,Gender,Age,Married,Number of Dependents,Latitude,Longitude,Number of Referrals,Tenure in Months,Phone Service,Avg Monthly Long Distance Charges,...,Churn Reason_Lack of self-service on Website,Churn Reason_Limited range of services,Churn Reason_Long distance charges,Churn Reason_Moved,Churn Reason_Network reliability,Churn Reason_Poor expertise of online support,Churn Reason_Poor expertise of phone support,Churn Reason_Price too high,Churn Reason_Product dissatisfaction,Churn Reason_Service dissatisfaction
25,1,37,1,1,33.309852,-116.823091,1,1,0,25.420517,...,False,False,False,False,False,False,False,False,False,False
26,1,37,1,3,36.622237,-119.521126,10,55,1,35.040000,...,False,False,False,False,False,False,False,False,False,False
27,0,42,1,3,37.612612,-121.108568,3,54,1,19.700000,...,False,False,False,False,False,False,False,False,False,False
28,0,64,0,0,38.368744,-122.522642,0,26,1,37.700000,...,False,False,False,False,False,False,False,False,False,False
29,1,47,1,3,40.737431,-124.108897,5,69,1,38.390000,...,False,False,False,False,False,False,False,False,False,False
30,0,23,1,3,37.515556,-122.502311,1,37,1,43.010000,...,False,False,False,False,False,False,False,False,False,False
31,1,48,1,0,34.001617,-118.222274,5,49,1,49.580000,...,False,False,False,False,False,False,False,False,False,False
32,0,28,1,0,34.044271,-118.185237,9,66,1,43.770000,...,False,False,False,False,False,False,False,False,False,False
33,1,28,0,0,32.690654,-115.431225,0,67,1,23.120000,...,False,False,False,False,False,False,False,False,False,False
34,0,33,1,1,40.677649,-122.294670,4,20,0,25.420517,...,False,False,False,False,False,False,False,False,False,False
35,1,31,0,3,37.084697,-121.606417,0,43,1,30.640000,...,False,False,False,False,False,False,False,False,False,False
36,1,37,1,0,38.044523,-121.348048,2,55,1,5.080000,...,False,False,False,False,False,False,False,False,False,False
37,1,60,1,0,33.964131,-118.272783,4,59,1,16.390000,...,False,False,False,False,False,False,False,False,False,False
38,1,48,1,3,33.978030,-118.217141,3,12,1,19.280000,...,False,False,False,False,False,False,False,False,False,False
39,0,60,1,3,35.013299,-116.834092,7,27,1,25.260000,...,False,False,False,False,False,False,False,False,False,False
40,0,69,0,0,32.961064,-117.134917,0,2,1,43.990000,...,False,False,False,False,False,False,False,False,False,False
41,1,20,0,0,37.516791,-121.899117,0,27,1,48.910000,...,False,False,False,False,False,False,False,False,False,False
42,0,31,1,3,38.439696,-122.668817,1,25,1,23.690000,...,False,False,False,False,False,False,False,False,False,False
43,0,46,1,0,37.327069,-121.916819,5,25,1,6.450000,...,False,False,False,False,False,False,False,False,False,False
44,0,57,0,1,34.296574,-118.244839,0,29,0,25.420517,...,False,False,False,False,False,False,False,False,False,False
45,0,19,1,0,36.391777,-119.372842,5,72,1,32.360000,...,False,False,False,False,False,False,False,False,False,False
46,1,64,0,0,38.123544,-121.159078,0,14,1,24.040000,...,False,False,False,False,False,False,False,False,False,False
47,1,38,0,0,37.654551,-119.822984,0,35,1,36.420000,...,False,False,False,False,False,False,False,False,False,False
48,0,54,0,0,38.629618,-122.593216,0,1,1,42.950000,...,False,False,False,False,False,False,False,False,False,False
49,0,50,0,0,37.956963,-120.863055,0,29,1,2.050000,...,False,False,False,False,False,False,False,False,False,False
50,0,25,0,0,41.813521,-121.492666,0,64,1,5.490000,...,False,False,False,False,False,False,False,False,False,False
51,1,35,1,3,38.425280,-119.475741,1,39,1,24.380000,...,False,False,False,False,False,False,False,False,False,False
52,1,72,0,0,34.581308,-118.931948,0,40,1,44.140000,...,False,False,False,False,False,False,False,False,False,False
53,0,51,0,0,33.832799,-116.250973,0,40,1,37.690000,...,False,False,False,False,False,False,False,False,False,False
54,1,78,0,1,34.207295,-118.400022,0,11,1,11.590000,...,False,False,False,False,False,False,False,False,True,False
55,1,30,1,0,38.099323,-122.945723,10,6,1,42.660000,...,False,False,False,False,False,False,False,False,False,False
56,0,58,0,0,38.526941,-122.709096,0,30,1,2.640000,...,False,False,False,False,False,False,False,False,False,False
57,0,26,0,0,37.387027,-121.897775,0,27,1,20.660000,...,False,False,False,False,False,False,False,False,False,False
58,0,66,1,0,33.782068,-118.262263,3,70,1,39.490000,...,False,False,False,False,False,False,False,False,False,False
59,1,20,1,0,37.670526,-120.877572,10,57,1,8.010000,...,False,False,False,False,False,False,False,False,False,False
60,0,61,1,0,32.697098,-117.116587,10,58,1,18.370000,...,False,False,False,False,False,False,False,False,False,False
61,0,24,0,0,33.753146,-118.367459,0,16,1,25.710000,...,False,False,False,False,False,False,False,False,False,False
62,1,55,1,0,38.419525,-122.521585,3,69,1,38.520000,...,False,False,False,False,False,False,False,False,False,False
63,0,32,0,0,38.419350,-120.469545,0,1,1,31.770000,...,False,False,False,False,False,False,False,False,False,False
64,0,59,0,0,34.003553,-118.308933,0,1,1,40.710000,...,False,False,False,False,False,False,False,False,False,False
65,0,71,1,1,34.097863,-116.594561,9,32,1,31.860000,...,False,False,False,False,False,False,False,False,False,False
66,0,49,1,2,33.324900,-114.758334,8,16,1,48.710000,...,False,False,False,False,False,False,False,False,False,False
67,0,61,1,0,34.395830,-117.734568,1,49,1,39.550000,...,False,False,False,False,False,False,False,False,False,False
68,1,40,1,0,35.591387,-121.032256,2,71,0,25.420517,...,False,False,False,False,False,False,False,False,False,False
69,1,39,0,0,40.923558,-122.059933,0,33,1,49.690000,...,False,False,False,False,False,False,False,False,False,False
70,1,21,1,0,41.572813,-124.035011,9,10,1,49.600000,...,False,False,False,False,False,False,False,False,False,False
71,0,24,1,0,36.841655,-119.797113,1,21,1,36.260000,...,False,False,False,False,False,False,False,False,False,False
72,0,52,1,1,38.542448,-122.419923,1,37,0,25.420517,...,False,False,False,False,False,False,False,False,False,False
73,1,71,0,0,37.249377,-120.249581,0,26,1,33.740000,...,False,False,False,False,False,False,False,False,False,False
74,0,45,0,0,40.142256,-123.852927,0,50,0,25.420517,...,False,False,False,False,False,False,False,False,False,False
75,1,29,0,0,32.857230,-117.209774,0,7,1,28.620000,...,False,False,False,False,False,False,False,False,False,False
76,1,62,1,0,34.049172,-118.115022,1,61,1,47.190000,...,False,False,False,False,False,False,False,False,False,False
77,0,42,0,0,37.818589,-120.256995,0,15,1,45.920000,...,False,False,False,False,False,False,False,False,False,False

In [74]:
tel_df.drop_duplicates(keep='last')

,Gender,Age,Married,Number of Dependents,Latitude,Longitude,Number of Referrals,Tenure in Months,Phone Service,Avg Monthly Long Distance Charges,...,Churn Reason_Lack of self-service on Website,Churn Reason_Limited range of services,Churn Reason_Long distance charges,Churn Reason_Moved,Churn Reason_Network reliability,Churn Reason_Poor expertise of online support,Churn Reason_Poor expertise of phone support,Churn Reason_Price too high,Churn Reason_Product dissatisfaction,Churn Reason_Service dissatisfaction
25,1,37,1,1,33.309852,-116.823091,1,1,0,25.420517,...,False,False,False,False,False,False,False,False,False,False
26,1,37,1,3,36.622237,-119.521126,10,55,1,35.040000,...,False,False,False,False,False,False,False,False,False,False
27,0,42,1,3,37.612612,-121.108568,3,54,1,19.700000,...,False,False,False,False,False,False,False,False,False,False
28,0,64,0,0,38.368744,-122.522642,0,26,1,37.700000,...,False,False,False,False,False,False,False,False,False,False
29,1,47,1,3,40.737431,-124.108897,5,69,1,38.390000,...,False,False,False,False,False,False,False,False,False,False
30,0,23,1,3,37.515556,-122.502311,1,37,1,43.010000,...,False,False,False,False,False,False,False,False,False,False
31,1,48,1,0,34.001617,-118.222274,5,49,1,49.580000,...,False,False,False,False,False,False,False,False,False,False
32,0,28,1,0,34.044271,-118.185237,9,66,1,43.770000,...,False,False,False,False,False,False,False,False,False,False
33,1,28,0,0,32.690654,-115.431225,0,67,1,23.120000,...,False,False,False,False,False,False,False,False,False,False
34,0,33,1,1,40.677649,-122.294670,4,20,0,25.420517,...,False,False,False,False,False,False,False,False,False,False
35,1,31,0,3,37.084697,-121.606417,0,43,1,30.640000,...,False,False,False,False,False,False,False,False,False,False
36,1,37,1,0,38.044523,-121.348048,2,55,1,5.080000,...,False,False,False,False,False,False,False,False,False,False
37,1,60,1,0,33.964131,-118.272783,4,59,1,16.390000,...,False,False,False,False,False,False,False,False,False,False
38,1,48,1,3,33.978030,-118.217141,3,12,1,19.280000,...,False,False,False,False,False,False,False,False,False,False
39,0,60,1,3,35.013299,-116.834092,7,27,1,25.260000,...,False,False,False,False,False,False,False,False,False,False
40,0,69,0,0,32.961064,-117.134917,0,2,1,43.990000,...,False,False,False,False,False,False,False,False,False,False
41,1,20,0,0,37.516791,-121.899117,0,27,1,48.910000,...,False,False,False,False,False,False,False,False,False,False
42,0,31,1,3,38.439696,-122.668817,1,25,1,23.690000,...,False,False,False,False,False,False,False,False,False,False
43,0,46,1,0,37.327069,-121.916819,5,25,1,6.450000,...,False,False,False,False,False,False,False,False,False,False
44,0,57,0,1,34.296574,-118.244839,0,29,0,25.420517,...,False,False,False,False,False,False,False,False,False,False
45,0,19,1,0,36.391777,-119.372842,5,72,1,32.360000,...,False,False,False,False,False,False,False,False,False,False
46,1,64,0,0,38.123544,-121.159078,0,14,1,24.040000,...,False,False,False,False,False,False,False,False,False,False
47,1,38,0,0,37.654551,-119.822984,0,35,1,36.420000,...,False,False,False,False,False,False,False,False,False,False
48,0,54,0,0,38.629618,-122.593216,0,1,1,42.950000,...,False,False,False,False,False,False,False,False,False,False
49,0,50,0,0,37.956963,-120.863055,0,29,1,2.050000,...,False,False,False,False,False,False,False,False,False,False
50,0,25,0,0,41.813521,-121.492666,0,64,1,5.490000,...,False,False,False,False,False,False,False,False,False,False
51,1,35,1,3,38.425280,-119.475741,1,39,1,24.380000,...,False,False,False,False,False,False,False,False,False,False
52,1,72,0,0,34.581308,-118.931948,0,40,1,44.140000,...,False,False,False,False,False,False,False,False,False,False
53,0,51,0,0,33.832799,-116.250973,0,40,1,37.690000,...,False,False,False,False,False,False,False,False,False,False
54,1,78,0,1,34.207295,-118.400022,0,11,1,11.590000,...,False,False,False,False,False,False,False,False,True,False
55,1,30,1,0,38.099323,-122.945723,10,6,1,42.660000,...,False,False,False,False,False,False,False,False,False,False
56,0,58,0,0,38.526941,-122.709096,0,30,1,2.640000,...,False,False,False,False,False,False,False,False,False,False
57,0,26,0,0,37.387027,-121.897775,0,27,1,20.660000,...,False,False,False,False,False,False,False,False,False,False
58,0,66,1,0,33.782068,-118.262263,3,70,1,39.490000,...,False,False,False,False,False,False,False,False,False,False
59,1,20,1,0,37.670526,-120.877572,10,57,1,8.010000,...,False,False,False,False,False,False,False,False,False,False
60,0,61,1,0,32.697098,-117.116587,10,58,1,18.370000,...,False,False,False,False,False,False,False,False,False,False
61,0,24,0,0,33.753146,-118.367459,0,16,1,25.710000,...,False,False,False,False,False,False,False,False,False,False
62,1,55,1,0,38.419525,-122.521585,3,69,1,38.520000,...,False,False,False,False,False,False,False,False,False,False
63,0,32,0,0,38.419350,-120.469545,0,1,1,31.770000,...,False,False,False,False,False,False,False,False,False,False
64,0,59,0,0,34.003553,-118.308933,0,1,1,40.710000,...,False,False,False,False,False,False,False,False,False,False
65,0,71,1,1,34.097863,-116.594561,9,32,1,31.860000,...,False,False,False,False,False,False,False,False,False,False
66,0,49,1,2,33.324900,-114.758334,8,16,1,48.710000,...,False,False,False,False,False,False,False,False,False,False
67,0,61,1,0,34.395830,-117.734568,1,49,1,39.550000,...,False,False,False,False,False,False,False,False,False,False
68,1,40,1,0,35.591387,-121.032256,2,71,0,25.420517,...,False,False,False,False,False,False,False,False,False,False
69,1,39,0,0,40.923558,-122.059933,0,33,1,49.690000,...,False,False,False,False,False,False,False,False,False,False
70,1,21,1,0,41.572813,-124.035011,9,10,1,49.600000,...,False,False,False,False,False,False,False,False,False,False
71,0,24,1,0,36.841655,-119.797113,1,21,1,36.260000,...,False,False,False,False,False,False,False,False,False,False
72,0,52,1,1,38.542448,-122.419923,1,37,0,25.420517,...,False,False,False,False,False,False,False,False,False,False
73,1,71,0,0,37.249377,-120.249581,0,26,1,33.740000,...,False,False,False,False,False,False,False,False,False,False
74,0,45,0,0,40.142256,-123.852927,0,50,0,25.420517,...,False,False,False,False,False,False,False,False,False,False
75,1,29,0,0,32.857230,-117.209774,0,7,1,28.620000,...,False,False,False,False,False,False,False,False,False,False
76,1,62,1,0,34.049172,-118.115022,1,61,1,47.190000,...,False,False,False,False,False,False,False,False,False,False
77,0,42,0,0,37.818589,-120.256995,0,15,1,45.920000,...,False,False,False,False,False,False,False,False,False,False

In [75]:
tel_df.drop_duplicates(subset=['Gender'])

,Gender,Age,Married,Number of Dependents,Latitude,Longitude,Number of Referrals,Tenure in Months,Phone Service,Avg Monthly Long Distance Charges,...,Churn Reason_Lack of self-service on Website,Churn Reason_Limited range of services,Churn Reason_Long distance charges,Churn Reason_Moved,Churn Reason_Network reliability,Churn Reason_Poor expertise of online support,Churn Reason_Poor expertise of phone support,Churn Reason_Price too high,Churn Reason_Product dissatisfaction,Churn Reason_Service dissatisfaction
25,1,37,1,1,33.309852,-116.823091,1,1,0,25.420517,...,False,False,False,False,False,False,False,False,False,False
27,0,42,1,3,37.612612,-121.108568,3,54,1,19.700000,...,False,False,False,False,False,False,False,False,False,False

In [76]:
df["Longitude"].astype('float32')

0      -118.999069
1      -118.203873
2      -117.922615
3      -122.115433
4      -119.079903
           ...
7038   -116.997261
7039   -120.954269
7040   -123.645119
7041   -117.263626
7042   -120.636360
Name: Longitude, Length: 7043, dtype: float32

In [77]:
df.duplicated().sum()

0

In [78]:
df.drop_duplicates(inplace=True)
df

,Gender,Age,Married,Number of Dependents,Latitude,Longitude,Number of Referrals,Tenure in Months,Phone Service,Avg Monthly Long Distance Charges,...,Churn Reason_Lack of self-service on Website,Churn Reason_Limited range of services,Churn Reason_Long distance charges,Churn Reason_Moved,Churn Reason_Network reliability,Churn Reason_Poor expertise of online support,Churn Reason_Poor expertise of phone support,Churn Reason_Price too high,Churn Reason_Product dissatisfaction,Churn Reason_Service dissatisfaction
0,1,37,1,0,34.827662,-118.999073,2,9,1,42.390000,...,False,False,False,False,False,False,False,False,False,False
1,0,46,0,0,34.162515,-118.203869,0,9,1,10.690000,...,False,False,False,False,False,False,False,False,False,False
2,0,50,0,0,33.645672,-117.922613,0,4,1,33.650000,...,False,False,False,False,False,False,False,False,False,False
3,0,78,1,0,38.014457,-122.115432,1,13,1,27.820000,...,False,False,False,False,False,False,False,False,True,False
4,1,75,1,0,34.227846,-119.079903,3,3,1,7.380000,...,False,False,False,False,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,1,20,0,0,32.759327,-116.997260,0,13,1,46.680000,...,False,False,False,False,False,False,False,False,False,False
7039,0,40,1,0,37.734971,-120.954271,1,22,1,16.200000,...,False,False,False,False,False,False,False,False,True,False
7040,0,22,0,0,39.108252,-123.645121,0,2,1,18.620000,...,False,False,False,False,False,False,False,False,False,False
7041,0,21,1,0,33.001813,-117.263628,5,67,1,2.120000,...,False,False,False,False,False,False,False,False,False,False
7042,0,36,1,0,39.600599,-120.636358,1,63,0,25.420517,...,False,False,False,False,False,False,False,False,False,False

In [79]:
df['Gender'] = pd.to_numeric(df['Gender'], errors='coerce')
df

,Gender,Age,Married,Number of Dependents,Latitude,Longitude,Number of Referrals,Tenure in Months,Phone Service,Avg Monthly Long Distance Charges,...,Churn Reason_Lack of self-service on Website,Churn Reason_Limited range of services,Churn Reason_Long distance charges,Churn Reason_Moved,Churn Reason_Network reliability,Churn Reason_Poor expertise of online support,Churn Reason_Poor expertise of phone support,Churn Reason_Price too high,Churn Reason_Product dissatisfaction,Churn Reason_Service dissatisfaction
0,1,37,1,0,34.827662,-118.999073,2,9,1,42.390000,...,False,False,False,False,False,False,False,False,False,False
1,0,46,0,0,34.162515,-118.203869,0,9,1,10.690000,...,False,False,False,False,False,False,False,False,False,False
2,0,50,0,0,33.645672,-117.922613,0,4,1,33.650000,...,False,False,False,False,False,False,False,False,False,False
3,0,78,1,0,38.014457,-122.115432,1,13,1,27.820000,...,False,False,False,False,False,False,False,False,True,False
4,1,75,1,0,34.227846,-119.079903,3,3,1,7.380000,...,False,False,False,False,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,1,20,0,0,32.759327,-116.997260,0,13,1,46.680000,...,False,False,False,False,False,False,False,False,False,False
7039,0,40,1,0,37.734971,-120.954271,1,22,1,16.200000,...,False,False,False,False,False,False,False,False,True,False
7040,0,22,0,0,39.108252,-123.645121,0,2,1,18.620000,...,False,False,False,False,False,False,False,False,False,False
7041,0,21,1,0,33.001813,-117.263628,5,67,1,2.120000,...,False,False,False,False,False,False,False,False,False,False
7042,0,36,1,0,39.600599,-120.636358,1,63,0,25.420517,...,False,False,False,False,False,False,False,False,False,False

Remove Negative Values

In [80]:
df['Monthly Charge'] = df['Monthly Charge'].abs()
df['Monthly Charge']

0       65.60
1        4.00
2       73.90
3       98.00
4       83.90
        ...
7038    55.15
7039    85.10
7040    50.30
7041    67.85
7042    59.00
Name: Monthly Charge, Length: 7043, dtype: float64

*For converting all numeric columns into positive at a time*

In [81]:
#num_cols = df.select_dtypes(include=['int64','float64']).columns
#df[num_cols] = df[num_cols].abs()

FOR CHECKING HOW MANY NEGATIVE VALUES IN THE COLUMN

In [82]:
for col in df.select_dtypes(include=['int64','float64']).columns:
    neg_count = (df[col] < 0).sum()
    if neg_count > 0:
        print(col, "has", neg_count, "negative values")

Longitude has 7043 negative values

In [83]:
df

,Gender,Age,Married,Number of Dependents,Latitude,Longitude,Number of Referrals,Tenure in Months,Phone Service,Avg Monthly Long Distance Charges,...,Churn Reason_Lack of self-service on Website,Churn Reason_Limited range of services,Churn Reason_Long distance charges,Churn Reason_Moved,Churn Reason_Network reliability,Churn Reason_Poor expertise of online support,Churn Reason_Poor expertise of phone support,Churn Reason_Price too high,Churn Reason_Product dissatisfaction,Churn Reason_Service dissatisfaction
0,1,37,1,0,34.827662,-118.999073,2,9,1,42.390000,...,False,False,False,False,False,False,False,False,False,False
1,0,46,0,0,34.162515,-118.203869,0,9,1,10.690000,...,False,False,False,False,False,False,False,False,False,False
2,0,50,0,0,33.645672,-117.922613,0,4,1,33.650000,...,False,False,False,False,False,False,False,False,False,False
3,0,78,1,0,38.014457,-122.115432,1,13,1,27.820000,...,False,False,False,False,False,False,False,False,True,False
4,1,75,1,0,34.227846,-119.079903,3,3,1,7.380000,...,False,False,False,False,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,1,20,0,0,32.759327,-116.997260,0,13,1,46.680000,...,False,False,False,False,False,False,False,False,False,False
7039,0,40,1,0,37.734971,-120.954271,1,22,1,16.200000,...,False,False,False,False,False,False,False,False,True,False
7040,0,22,0,0,39.108252,-123.645121,0,2,1,18.620000,...,False,False,False,False,False,False,False,False,False,False
7041,0,21,1,0,33.001813,-117.263628,5,67,1,2.120000,...,False,False,False,False,False,False,False,False,False,False
7042,0,36,1,0,39.600599,-120.636358,1,63,0,25.420517,...,False,False,False,False,False,False,False,False,False,False

Data Formating

*covert to date*

In [84]:
#df["date"] = pd.to_datetime(df["date"])

convert to float

In [85]:
df["Avg Monthly GB Download"] = df["Avg Monthly GB Download"].astype(float)
df['Avg Monthly GB Download']

0       16.0
1       10.0
2       30.0
3        4.0
4       11.0
        ...
7038    59.0
7039    17.0
7040    51.0
7041    58.0
7042     5.0
Name: Avg Monthly GB Download, Length: 7043, dtype: float64

convert to int

In [86]:
df["Gender"] = df["Gender"].astype(int)

In [87]:
df['Online Security']=df['Online Security'].astype(int)

In [88]:
df['Online Backup']=df['Online Backup'].astype(int)

NORMALIZATION (min-max)

In [89]:
#df["Monthly Charge"] = (df["Monthly Charge"] - df["Monthly Charge"].min()) / (df["Monthly Charge"].max() - df["Monthly Charge"].min())
#df["Monthly Charge"]
#df["Total Charges"] = (df["Total Charges"] - df["Total Charges"].min()) / (df["Total Charges"].max() - df["Total Charges"].min())
#df["Total Charges"]
#df["Tenure in Months"] = (df["Tenure in Months"] - df["Tenure in Months"].min()) / (df["Tenure in Months"].max() - df["Tenure in Months"].min())
#df["Tenure in Months"]

Binning

In [90]:
bins = [0, 18, 35, 60, 100]
labels = ["Child", "Young", "Adult", "Senior"]

df["age_group"] = pd.cut(df["Age"], bins=bins, labels=labels)

OUTLIERS HANDLING

->we are calculating lower limit  and upper limit..

->below lower limit and above upper limit is considerd as outlier..

->by using  IQR method(INTER QUARTILE RANGE).

In [91]:
Q1=df['Monthly Charge'].quantile(0.25)
Q3=df['Monthly Charge'].quantile(0.75)
IQR=Q3-Q1
lower=Q1-1.5*IQR
upper=Q3+1.5*IQR
outliers=df[(df["Monthly Charge"]<lower)|(df['Monthly Charge']>upper)]
print(len(outliers))

0

In [92]:
Q1=df['Total Charges'].quantile(0.25)
Q3=df['Total Charges'].quantile(0.75)
IQR=Q3-Q1
lower=Q1-1.5*IQR
upper=Q3+1.5*IQR
outliers=df[(df["Total Charges"]<lower)|(df['Total Charges']>upper)]
print(len(outliers))

0

Feature Engineering

Avg Monthly spend

In [93]:
df["avg_monthly_spend"] = df["Total Charges"] / (df['Tenure in Months'] + 1)

spending charge

In [94]:
df["spend_change"] = df["Monthly Charge"] - df["avg_monthly_spend"]

expensive customer

In [95]:
df["high_bill"] = (df["Monthly Charge"] > df["Monthly Charge"].median()).astype(int)

ROUNDING FLOAT VALUE

In [96]:
df=df.round(2)

In [97]:
df

,Gender,Age,Married,Number of Dependents,Latitude,Longitude,Number of Referrals,Tenure in Months,Phone Service,Avg Monthly Long Distance Charges,...,Churn Reason_Network reliability,Churn Reason_Poor expertise of online support,Churn Reason_Poor expertise of phone support,Churn Reason_Price too high,Churn Reason_Product dissatisfaction,Churn Reason_Service dissatisfaction,age_group,avg_monthly_spend,spend_change,high_bill
0,1,37,1,0,34.83,-119.00,2,9,1,42.39,...,False,False,False,False,False,False,Adult,59.33,6.27,0
1,0,46,0,0,34.16,-118.20,0,9,1,10.69,...,False,False,False,False,False,False,Adult,54.24,-50.24,0
2,0,50,0,0,33.65,-117.92,0,4,1,33.65,...,False,False,False,False,False,False,Adult,56.17,17.73,1
3,0,78,1,0,38.01,-122.12,1,13,1,27.82,...,False,False,False,False,True,False,Senior,88.42,9.58,1
4,1,75,1,0,34.23,-119.08,3,3,1,7.38,...,True,False,False,False,False,False,Senior,66.85,17.05,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,1,20,0,0,32.76,-117.00,0,13,1,46.68,...,False,False,False,False,False,False,Young,53.06,2.09,0
7039,0,40,1,0,37.73,-120.95,1,22,1,16.20,...,False,False,False,False,True,False,Adult,81.47,3.63,1
7040,0,22,0,0,39.11,-123.65,0,2,1,18.62,...,False,False,False,False,False,False,Young,30.92,19.38,0
7041,0,21,1,0,33.00,-117.26,5,67,1,2.12,...,False,False,False,False,False,False,Young,68.05,-0.20,0
7042,0,36,1,0,39.60,-120.64,1,63,0,25.42,...,False,False,False,False,False,False,Adult,57.93,1.07,0

In [98]:
df.to_csv("cleaned.csv", index=False)